### ISSUE TITLE
Не работает распаковка внешних обработок с русскими именами в нелокализованной под русский язык системе

### ISSUE THREAD

**Issue by KalyakinAG** [xDrivenDevelopment/precommit1c#107]
Коллеги, попробовал использовать данное решение и обнаружил, что в windows 10 не работает распаковка внешних обработок с русскими именами.
Так, при выполнении commit у меня выскакивает сообщение 1С: "Результат распаковки не является результатом распаковки для файла обработки". При этом в логе v8files-extractor.log ошибок не фиксируется, просто в каталоге исходников пустой каталог и пустые файлы:
             3 maps.txt
             3 renames.txt
<DIR>          und
Попробовал вручную распаковать внешнюю обработку:
C:\utils\V8Unpack>dir
 Volume in drive C is Windows 10
 Volume Serial Number is 905D-2DA8

 Directory of C:\utils\V8Unpack

25-Feb-17  14:59    <DIR>          .
25-Feb-17  14:59    <DIR>          ..
06-Feb-17  22:11             5,643 ExternalProcessing1.epf
25-Feb-17  14:38    <DIR>          src
05-Feb-17  15:54           800,256 v8unpack.exe
06-Feb-17  22:11             5,643 ВнешнаяяОбработка1.epf
               3 File(s)        811,542 bytes
               3 Dir(s)  24,954,482,688 bytes free

C:\utils\V8Unpack>v8Unpack.exe -p "c:\utils\V8unpack\ВнешнаяяОбработка1.epf" c:\utils\V8Unpack\src
UnpackToFolder. Input file not found!

C:\utils\V8Unpack>v8Unpack.exe -p "c:\utils\V8unpack\ExternalProcessing1.epf" c:\utils\V8Unpack\src
LoadFile: ok

Была установлена версия 1С 8.3.8, потом установил 8.3.9 - результат тотже.

**Comment by nixel2007** [comment]
Требования по настройке гита из ридми выполняли?

**Comment by KalyakinAG** [comment]
Да, вот настройки гит из config:
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	quotepath = false

**Comment by KalyakinAG** [comment]
Я использую триальную windows 10, виртуальный образ которой можно скачать бесплатно с сайта microsoft.

**Comment by KalyakinAG** [comment]
Попробовал поставить виртуальную машину на win7 - ситуация такая же.

**Comment by KalyakinAG** [comment]
В обоих случаях windows не локализована под русский язык

**Comment by KalyakinAG** [comment]
На рабочем компе стоит локализованная версия win7, precommit1c отрабатывает без ошибок, однако v8unpack также не видит обработку с русским именем.

**Comment by bambr1975** [comment]
https://gitter.im/xDrivenDevelopment/precommit1c?at=57bd511eed79c5ee4f30cdea

**Comment by KalyakinAG** [comment]
Ок! Спасибо!

**Comment by artbear** [comment]
Для истории

> Уф... Целая эпопея получилась. Но может кому поможет в дальнейшем. В очередной раз попросил админов поразбираться. Выставили как на картинке в Панель управления\Все элементы панели управления\Язык и там "Дополнительные параметры". В них русский для программ не поддерживающий Юникод. И заработало...
> [![Снимок.PNG](https://files.gitter.im/xDrivenDevelopment/precommit1c/zsE2/thumb/______.png)](https://files.gitter.im/xDrivenDevelopment/precommit1c/zsE2/______.PNG)

**Comment by artbear** [comment]
Чтобы в гиттер не ходить
