### ISSUE TITLE
Распаковка на платформе 8.3.9+

### ISSUE THREAD

**Issue by theshadowco** [xDrivenDevelopment/precommit1c#108]
При наличии старших версий платформы при открытии обработок срабатывают проверки на безопастность исполнения внешней обработки и запуска ей бинарника. 

Стоит доработать, чтобы подключение обработки происходило в небезопасном режиме без вопросов пользователю.

**Comment by nixel2007** [comment]
Вроде это уже в ридми прописано. Обработка ничего не может с собой сделать, чтобы выключить эту проверку

**Comment by artbear** [comment]
Описание есть в девелоп https://github.com/xDrivenDevelopment/precommit1c/tree/develop#Для-корректной-работы-на-1С-версии-8392016-и-старше

В мастере нет этого описания. ИМХО от этого и ошибки.

Нужно выпустить релиз
