### ISSUE TITLE
Некорректно отрабатывает разбор

### ISSUE THREAD

**Issue by 1cgh** [xDrivenDevelopment/precommit1c#111]
Установлен прекоммит по инструкции.
Изменяю epf-файл.
Добавляю в stage
Делаю commit
Срабатывает хук.
У обработки в сырцах удаляется модуль объекта.
Файл обработки в зипе в архиве.
[vanessa-behavior.zip](https://github.com/xDrivenDevelopment/precommit1c/files/824602/vanessa-behavior.zip)
1С 8.3.9.2170
Проявляется и на 2.0.6 из master и на 2.2.0 из develop

Также в порядке эксперимента при коммите оставлял пустой commit message (в этом случае коммит отменяется). Файлы в src после отмены оставались измененными, модуля объекта нет, в stage помимо epf куча файлов из src. Вот такой лог, например:

> a.nenashev@pc016 MINGW32 /c/GIT/1cgh/vanessa-behavior (develop)
> $ git commit
> Start hooks before commit for v8unpack erf and epf
> ИНФОРМАЦИЯ - precommit1c v2.2.0
> 
> ИНФОРМАЦИЯ - Проверка необходимости выгрузки файла C:\GIT\1cgh\vanessa-behavior\vanessa-behavior.epf в каталог C:\GIT\1cgh\vanessa-behavior\src, корень C:\GIT\1cgh\vanessa-behavior
> ИНФОРМАЦИЯ - Завершена проверка необходимости выгрузки файла C:\GIT\1cgh\vanessa-behavior\vanessa-behavior.epf в каталог C:\GIT\1cgh\vanessa-behavior\src, корень C:\GIT\1cgh\vanessa-behavior
> Aborting commit due to empty commit message.
> 
> a.nenashev@pc016 MINGW32 /c/GIT/1cgh/vanessa-behavior (develop)
> $ git status
> On branch develop
> Your branch is up-to-date with 'origin/develop'.
> Changes to be committed:
>   (use "git reset HEAD <file>..." to unstage)
> 
>         modified:   src/vanessa-behavior/Form/ЗаписьJSON/form
>         modified:   src/vanessa-behavior/Form/Форма/form
>         deleted:    src/vanessa-behavior/ObjectModule.bsl
>         modified:   src/vanessa-behavior/renames.txt
>         deleted:    src/vanessa-behavior/und/baaa3cdd-acc2-4c98-8ab3-94286ca266a3.0/info
>         modified:   src/vanessa-behavior/und/f8ab9b72-2202-4d81-a8c5-f1389f22100f
>         modified:   src/vanessa-behavior/und/version
>         modified:   src/vanessa-behavior/und/versions
>         modified:   vanessa-behavior.epf
> 
>

**Comment by artbear** [comment]
>Также в порядке эксперимента при коммите оставлял пустой commit message (в этом случае коммит отменяется)

У нас в прекоммите при пустом комментарии коммит не отменяется.
Возможно, у тебя допиленный прекоммит? или еще какой-то хук стоит?

**Comment by artbear** [comment]
а если руками запустить `precommit1c --git-precommit src` ?
те же сообщения?

**Comment by 1cgh** [comment]
@artbear Отмена коммита при пустом комментарии - это вроде как стандартное поведение гита.
Если руками запустить precommit1c --git-precommit src, то разбирается корректно.

**Comment by nixel2007** [comment]
> У нас в прекоммите при пустом комментарии коммит не отменяется.

с гитсинком путаешь

**Comment by bambr1975** [comment]
проблема V8reader. Подтверждаю. Постараюсь до завтра разобраться

**Comment by bambr1975** [comment]
попробуй взять https://github.com/xDrivenDevelopment/v8Reader/tree/develop отсюда
