### ISSUE TITLE
8.3.10 и 8.3.9. Выбирается младшая версия

### ISSUE THREAD

**Issue by git22ura** [xDrivenDevelopment/precommit1c#113]
На компе стоит 8.3.10.2*** и 8.3.9.2170. Стоит хук с прекомитом. При коммите 1с-обработки вызывается не самая старшая платформа 8.3.10, а 8.3.9.
Предположение, ибо раньше где-то сталкивался: 
10 младше 9, т.к. 1 меньше 9

**Comment by nixel2007** [comment]
`opm update v8runner` - обновит модуль, отвечающий за поиск платформы
