### ISSUE TITLE
Указывать версию платформы для разбора в параметрах

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/precommit1c#114]
Хотелось бы указывать версию платформы в конфигурационном файле для того, чтобы precommit1C использовал именно ее, а не автоматически подобранную.

**Comment by yarsergo** [comment]
у меня только 8.2 стоит

и при коммите из SourceTree  - ошибку выкинуло

т.е. precommit1c  - автоматически используется v8runner из библиотеки 1Script

C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os

и выдавало ошибку в 1355 строке 

ПутьКПлатформе1С(ПолучитьПутьКВерсииПлатформы("8.3"));


поменял у себя на 8.2  - всё прекрасно заработало!

**Comment by zeratulayuris** [comment]
реализовано параметром командной строки, через релиз будет конфигурационный файл.
