### ISSUE TITLE
Файл mlx не преобразуется в текст.

### ISSUE THREAD

**Issue by Pr-Mex** [xDrivenDevelopment/precommit1c#115]
Если происходит коммит файла mxl - то прекоммит не будет его конвертировать в текстовый формат.

**Comment by artbear** [comment]
Взял на себя, постараюсь сделать в какой-нибудь из вечером

**Comment by artbear** [comment]
@bambr1975 Я обновил v8reader в ветке develop на 1.13.2
https://github.com/xDrivenDevelopment/precommit1c/commit/9365fb04059d28bb69fc5173e94f7636bcf2b9c2

+ Создал пустой репо, гит инит, далее прекоммит --инсталл
+ Затем добавил файл Автозаполнение.mxl через git add .
+ Сделал гит коммит
```
W:\3>precommit1c --install                         
ИНФОРМАЦИЯ - precommit1c v2.1.0                    
                                                   
ИНФОРМАЦИЯ - Копирую: pre-commit                   
ИНФОРМАЦИЯ - Копирую: v8Reader                     
ИНФОРМАЦИЯ - Копирую: v8files-extractor.os         
ИНФОРМАЦИЯ - Копирую: tools                        
ИНФОРМАЦИЯ - Установка завершена                   
                                                   
W:\3>git add .                                     
                                                   
W:\3>git commit -m "init"                          
Start hooks before commit for v8unpack erf and epf 
ИНФОРМАЦИЯ - precommit1c v2.1.0                    
                                                   
[master (root-commit) 6920c19] init                
 1 file changed, 0 insertions(+), 0 deletions(-)   
 create mode 100644 Автозаполнение.mxl             
```

Доп.текстовый файл так и я не появился.
Что я делаю не так?

Посмотришь?

**Comment by bambr1975** [comment]
подскажи, какой командой ты вызываешь V8Reader
вторник, 12 сентября 2017 г. 10:33
Артур Аюханов
Привет! 
Штатной командой из precommit1c
Виктория Дорохина
Привет! я про то, что precommit не поддерживает mxl. Возьмешься допилить?
Артур Аюханов
в смысле не поддерживает? мхл-расширение при анализе гита пропускает, верно?
Виктория Дорохина
https://github.com/xDrivenDevelopment/precommit1c/blob/master/v8files-extractor.os#L233 верно

**Comment by artbear** [comment]
@bambr1975 https://github.com/xDrivenDevelopment/precommit1c/blob/master/v8files-extractor.os#L333

**Comment by artbear** [comment]
Ага, с первого раз тебя понял :(
Вечером исправлю

**Comment by zeratulayuris** [comment]
@bambr1975 вломился к тебе с PR, который поможет закрыть этот issue. В текущем виде не взлетает.

**Comment by zeratulayuris** [comment]
@artbear пинг

**Comment by artbear** [comment]
Выполнено
