### ISSUE TITLE
Отдельные MXL-файлы не раскладываются в текстовые файлы

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/precommit1c#116]
Раскладываются только mxl-файлы, входящие как макеты во внешние обработки.

@bambr1975 что скажешь? подтверждаешь?

**Comment by bambr1975** [comment]
Дубль https://github.com/xDrivenDevelopment/precommit1c/issues/115 До конца недели сделаю. До этого не было возможности.
