### ISSUE TITLE
Специальная сервисная база вместо автосоздаваемой файловой ИБ

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/precommit1c#120]
Часто неудобно юзать файловую базу, т.к. требуется клиентская лицензия 1С, которая может быть недоступна, если лицензии раздаются сервером.
Enterprise-команды нарывались.

**Comment by amwwind** [comment]
Так и осталось в заготовке? 

Пробовал Установить Контекст но не выполняется декомпиляция обработки в указанной базе, а все равно создает временную базу при коммите в git

Строка 342  v8files-extractor.os	
         Конфигуратор = Новый УправлениеКонфигуратором();
        //КаталогВременнойИБ = ВременныеФайлы.СоздатьКаталог();
	//Конфигуратор.КаталогСборки(КаталогВременнойИБ);
	СтрокаСоединения = "/IBConnectionString""Srvr=Server; Ref='database'""";
	Пользовтаель = """User""";
	Пароль = """passw0rd""";
	Конфигуратор.УстановитьКонтекст(СтрокаСоединения, Пользовтаель, Пароль);
	//


Если через командную строку запустить то отрабатывает в сервисной базе без ошибок.
oscript "C:\Program Files (x86)\OneScript\lib\precommit1c\v8files-extractor.os" --decompile "ПутьКОбработки\Обработка.epf" "Путь\src\lib\Обработки"

Подскажите как верно реализовать?

**Comment by artbear** [comment]
Выполнено в #124
