### ISSUE TITLE
Установка и использование на *nix

### ISSUE THREAD

**Issue by zeratulayuris** [xDrivenDevelopment/precommit1c#132]
Появился запрос на кроссплатформенность.
Разборку и сборку epf, erf и cfe можно выполнять конфигуратором, это делает возможным использование precommit1c под никсами, вопрос только в разборе mxl - он делается исключительно v8Reader'ом.

**Comment by zeratulayuris** [comment]
@bambr1975, получится переписать v8Reader так, чтобы com-объекты инициализировались попозже и mxl можно было разобрать без их инициализации?

**Comment by bambr1975** [comment]
ыыы. Был форк https://github.com/demidych/precommit1c от человека, который изначально написал v8unpack - там была попытка вообще не использовать V8reader, и делать весь разбор исключительно средствами OneScript, который, в отличии от платформы, умеет регулярные выражения без COM-объектов. И тогда платформу можно было бы дергать только для разбора mxl и V8reader здесь вообще был бы не нужен. Но к сожалению, человек все свои доработки из репозитория удалил. И вернуть их, видимо, можно только из локальной копии с моего компа. Но ее сначала надо найти, и, видимо, причесать ))) Я постараюсь заморочиться на этой неделе.

**Comment by bambr1975** [comment]
А mxl можно разбирать достаточно простой внешней обработкой, которая ничего не инициализирует при создании )))

**Comment by bambr1975** [comment]
видимо, нужно просто написать такую обработку и придумать, в каком месте существующего распаковщика ее вызывать.

**Comment by zeratulayuris** [comment]
Место уже точно есть, где вызывать. Так и сделаю тогда вечерком.

**Comment by zeratulayuris** [comment]
Решено в #150, выпускаю в тестовом режиме, однако.
