### ISSUE TITLE
Ошибка коммита mxl-файла

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/precommit1c#135]
У команды обучаемых возникла проблема - Ошибка коммита mxl-файла
- precommit1c 2.2.1
- OneScript 1.21.1

в продолжение https://github.com/xDrivenDevelopment/precommit1c/issues/115

![image](https://user-images.githubusercontent.com/2920817/55868947-26720100-5b8e-11e9-92e4-c0760981a9bc.png)

@zeratulayuris сталкивался с таким?

**Comment by zeratulayuris** [comment]
Тесты были недостаточно полными, для mxl не передаёт обратно правильное имя файла. Попробую сегодня запилить исправление.

**Comment by ripreal** [comment]
@artbear Натолкнулись на ту же ошибку. Просьба принять пулл-реквест.

**Comment by zeratulayuris** [comment]
@ripreal @artbear смержено.
