### ISSUE TITLE
как собрать внешнюю обработку из файлов

### ISSUE THREAD

**Issue by StratoCasterFen** [xDrivenDevelopment/precommit1c#142]
Команда precommit1c --compile D:\pro d:\pro\p1.epf 
выдает ошибку: Файл переименования d:\pro\renames.txt должен существовать}
Что должно быть в этом файле, какая его структура?
Где бы почитать описание ..

**Comment by nixel2007** [comment]
Сбор внешней обработки с помощью флага --compile возможен только для обработок, которые с помощью прекоммита и декомпилировались.
Если у вас обработка разбиралась конфигуратором, то и собирать ее надо конфигуратором или через vanessa-runner

**Comment by StratoCasterFen** [comment]
обработка разбиралась хуком precommit1c. Но я в полученном каталоге я не нашел файла renames.txt

**Comment by nixel2007** [comment]
хук работал в режиме designer или по старинке, через v8unpack?

**Comment by StratoCasterFen** [comment]
я делал так: precommit1c install
положил обработкуi
git add *
git commit
Отработал хук - разобрал обработку в папку src
а в каком режиме хук работал, я не знаю.

**Comment by StratoCasterFen** [comment]
Разобрался. если делать с параметром --use-designer.
тогда все разбирается и собирается обратно без ошибок

**Comment by zeratulayuris** [comment]
Закрываю.
