### ISSUE TITLE
Ошибка при коммите.

### ISSUE THREAD

**Issue by Bazooka2091** [xDrivenDevelopment/precommit1c#143]
{Модуль C:\Users\user1\Git\1c\MT\.git\hooks\v8files-extractor.os / Ошибка в строке: 668 / Внешнее исключение (System.IO.FileNotFoundException): Could not find file 'C:\Users\user1\AppData\Local\Temp\41tqxmyj.4mz.tmp'.}

В целом решается созданием файла до обращения к нему.

**Comment by zeratulayuris** [comment]
А есть подробный лог, что происходило? Файл должен был быть создан запущенной там же командой, но что-то пошло не так.

**Comment by Bazooka2091** [comment]
Уже нет, репозиторий удалил. В целом не так уж страшно, дописал проверку на наличие файла и создавал его в случае если его нет. Но потом вылезла другая проблема, а в следующем issue.
