### ISSUE TITLE
Ошибка: Не удалось собрать журнал изменений git

### ISSUE THREAD

**Issue by Bazooka2091** [xDrivenDevelopment/precommit1c#144]
{Модуль C:\Users\user1\Git\precommit1c\.git\hooks\v8files-extractor.os / Ошибка в строке: 633 / Не удалось собрать журнал изменений git}

Возвращает код 121 вместо 0

подробный лог: 

precommit1c(master): git commit -m "Test"
Start hooks before commit to unpack erf, epf and cfe
ИНФОРМАЦИЯ - precommit1c v2.2.1

ОТЛАДКА - ТипЗнч(Аргументы)= Структура
ОТЛАДКА - Передана команда: --git-precommit
ОТЛАДКА - --remove-orig-bin-files = Нет
ОТЛАДКА - --use-designer = Нет
ОТЛАДКА - ВыходнойКаталог = src
ОТЛАДКА - Текущий каталог C:\Users\user1\Git\precommit1c
ОТЛАДКА - Каталог выгрузки src
ОТЛАДКА - Выполняю команду git config core.quotepath
ОТЛАДКА - cmd /C "git config core.quotepath > "C:\temp\logOS\3a13ab1a-48ff-411a-9272-28ccc6695c4e.ptb.tmp" 2>&1"
ОТЛАДКА - Код возврата: 121
ОТЛАДКА -       Код возврата 121
ОТЛАДКА -       Вывод команды <>
ОТЛАДКА - Выполняю команду git config core.longpaths
ОТЛАДКА - cmd /C "git config core.longpaths > "C:\temp\logOS\1939e022-8a77-4012-8c1c-2fab7ff9fea2.ptb.tmp" 2>&1"
ОТЛАДКА - Код возврата: 121
ОТЛАДКА -       Код возврата 121
ОТЛАДКА -       Вывод команды <>
ОТЛАДКА - Запускаю git diff-index --name-status --cached HEAD
ОТЛАДКА - cmd /C "git diff-index --name-status --cached HEAD > "C:\temp\logOS\cbef3299-575c-451d-b60b-eb5f94082542.ptb.tmp" 2>&1"
ОТЛАДКА - Код возврата: 121
ОТЛАДКА -       Вывод команды гит:
ОТЛАДКА - Запускаю git status --porcelain
ОТЛАДКА - cmd /C "git status --porcelain > "C:\temp\logOS\ccdc4152-cbd4-4752-8fbc-00c7ade995b0.ptb.tmp" 2>&1"
ОТЛАДКА - Код возврата: 121
ОТЛАДКА -       Вывод команды гит:
ОШИБКА - {Модуль C:\Users\user1\Git\precommit1c\.git\hooks\v8files-extractor.os / Ошибка в строке: 633 / Не удалось собрать журнал изменений git}
ОТЛАДКА - Очищаем каталог временной ИБ
![2019-09-18_14-21-11](https://user-images.githubusercontent.com/55136750/65375313-6563c100-dcad-11e9-91e2-41d0ee195719.png)

**Comment by zeratulayuris** [comment]
Судя по логам, у вас git всё время возвращает 121. Похоже, что проблема именно с этим. Это поведение работает только в precommit или при любом запуске?

**Comment by Bazooka2091** [comment]
В других репозиториях вообще если выполнить этот кусочек кода тогда работает, похоже, как задумано. КодВозврата = 0  и вывод передается корректно. 

В precommit или там где устанавливаю хуки выдает запись как ранее. 
Собственно это на заметку, не по сути требовались исходники обработок что бы видеть изменения в гит, я не знал что есть стандартный функционал, напишу позже автоматизацию похожую на вашу, возможно форкну. 

На скриншоте результат выполнения. 
![2019-09-23_08-30-19](https://user-images.githubusercontent.com/55136750/65400643-cfc74f00-dddc-11e9-8961-47d88226db32.png)
