### ISSUE TITLE
Ошибка при первом коммите файла

### ISSUE THREAD

**Issue by ekaruk** [xDrivenDevelopment/precommit1c#15]
При первом коммите внешней обработки возникает ошибка:
fatal: ambiguous argument 'HEAD': unknown revision or patch not in the working tree.
![2014-11-17 00-13-19](https://cloud.githubusercontent.com/assets/9798170/5067027/0c736490-6e46-11e4-8f17-6cf43fac3d67.png)

**Comment by artbear** [comment]
Подтверждаю баг, только что нарвался на подобную ошибку для первого коммита, в котором участвуют внешние обработки.
Второй коммит проходит нормально.

**Comment by pumbaEO** [comment]
Ветка develop/master?

**Comment by artbear** [comment]
Да, в ветке девелоп проблема не подтверждается.
Закрываю
