### ISSUE TITLE
Инструмент не собирает обработку обратно из исходников

### ISSUE THREAD

**Issue by aleshko-dev** [xDrivenDevelopment/precommit1c#152]
При компилировании обработки из исходников выдает ошибку компиляции и не собирает ее.
Провел исследование и увидел что на этапе компиляции инструмент читает файл renames.txt и разбирает его на ключ-значение через разделитель "-->" методом СтрРазделить. Проблема в том что разделитель ищется посимвольно, а не целиком вся строка. И ошибка происходит когда встречается ГУИД объекта например строка ниже:
9e85d150-94c5-4925-88c1-0611ff9360d3-->und\9e85d150-94c5-4925-88c1-0611ff9360d3
Первый ключ в этом случае: 9e85d150 а значение 94c5. А дальше пытается найти файл в этой папке с именем равным значение.

Предлагаю добавить более редкий разделитель, чтобы избежать таких случаев. Например ===. Либо пересмотреть сам подход.

**Comment by zeratulayuris** [comment]
Дубль #141, в develop уже исправлено, в ближайшее время появится в релизе.

**Comment by zeratulayuris** [comment]
@aleshko-dev пробуйте свежий релиз :)
