### ISSUE TITLE
Ошибка при коммите, Библиотека не найдена cmdline}

### ISSUE THREAD

**Issue by Lisi4ka19** [xDrivenDevelopment/precommit1c#155]
Установлено OneScript - 1.3, precommit1c - 2.3, Sourcetree  - 3.1.2.
При попытке закоммитить в Sourcetree ошибка:
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks commit -q -F C:\Users\alisa\AppData\Local\Temp\2bgf4aqm.a5m
Start hooks before commit to unpack erf, epf and cfe
{Модуль E:\1С\resorce\all1c\.git\hooks\v8files-extractor.os / Ошибка в строке: 16,16 / Библиотека не найдена cmdline}

Подскажите, пожалуйста, что не так

**Comment by nixel2007** [comment]
День добрый. Как устанавливали прекоммит в репо?
Как устанавливали сам прекоммит?

**Comment by Lisi4ka19** [comment]
Добрый день!
 
Прекоммит клонировала с помощью Sourcetree себе на компьютер. 

Затем скопировала файлы: 
pre-commit
V8Reader
tools
v8files-extractor.os
в свой репозиторий, E:\1С\resorce\all1c\.git\hooks.

**Comment by nixel2007** [comment]
Попробуйте переустановить вот по этой инструкции:

https://github.com/xDrivenDevelopment/precommit1c#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-onescript-package-manager-%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D0%BE%D1%87%D1%82%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE

**Comment by zeratulayuris** [comment]
@Lisi4ka19 вы пропустили 4 шаг установки - зависимости из packagedef. Лучше использовать opm, как написал Никита.

**Comment by Lisi4ka19** [comment]
Спасибо, что так быстро откликнулись! Действительно, установка по первой схеме предпочтительней, все установилось само. Коммит прошел успешно, не пришлось даже перезапускать Sourcetree.
Спасибо!

**Comment by agaltsoff** [comment]
Подниму тему.

OneScript скопирован из zip архива в %USERPROFILE%\AppData\Local так как нет админских прав.

precommit1c установлен через opm

`opm i --dest %LOCALAPPDATA%\OneScript\lib precommit1c`

При установке установилось много библиотек из зависимостей, в том числе и cmdline в lib.

При коммите та же ошибка.

`git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks commit -q -F C:\Users\xxx\AppData\Local\Temp\kg0kuyzo.r4i
Start hooks before commit to unpack erf, epf and cfe
{Модуль C:\git\yyy\.git\hooks\v8files-extractor.os / Ошибка в строке: 16,16 / Библиотека не найдена cmdline}
Completed with errors, see above.
` 

В oscript.cfg прописал `lib.system = %LOCALAPPDATA%\OneScript\lib\`, не помогло.

**Comment by nixel2007** [comment]
Попробуйте положить oscript.cfg рядом с файлом v8files-extractor.os.

Как вариант, переехать на оскрипт, устанавливаемый через [ovm](https://github.com/oscript-library/ovm).
