### ISSUE TITLE
Обнаружено несоответствие базы cygheap

### ISSUE THREAD

**Issue by kasper076** [xDrivenDevelopment/precommit1c#159]
При выполнении Commit из Git GUI выдает следующее сообщение:

> 0 [main] sh (1600) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1C37408/0x1EF7408.
> This problem is probably due to using incompatible versions of the cygwin DLL.
> Search for cygwin1.dll using the Windows Start->Find/Search facility
> and delete all but the most recent version.  The most recent version *should*
> reside in x:\cygwin\bin, where 'x' is the drive on which you have
> installed the cygwin distribution.  Rebooting is also suggested if you
> are unable to find another cygwin DLL.

**Comment by EvilBeaver** [comment]
Это связано с конкретной инсталляцией ГИТа на конкретной машине. Корректировка/доработка precommit тут вряд ли как-то поможет.

**Comment by kasper076** [comment]
Понял. Спасибо.
А можете подсказать пути решения? Гул не оч помог.

**Comment by lybrus** [comment]
Переустановить git?

**Comment by kasper076** [comment]
Сначала установил 2.30. Получил эту ошибку. Почитал про эту проблему. Снес 2.30 и установил 2.25. Не помогло. В При установке выбрал редактор по умолчанию. Все остальное  по дефолту.

**Comment by lybrus** [comment]
При установке есть опция использовать git bash (точное название не помню), тогда sygwin не понадобится.

**Comment by kasper076** [comment]
![image](https://user-images.githubusercontent.com/11402408/103660641-e5836800-4f7e-11eb-9d85-60a10d84467f.png)
Судя по заголовку окна ругается на хук pre-commit
![image](https://user-images.githubusercontent.com/11402408/103664132-fb932780-4f82-11eb-87c2-99e783ff654b.png)
Вот эту настройку поменял.
Пробовал на версиях 2.03/2.25 64/32 bit

**Comment by lybrus** [comment]
Это не то, имел в виду установить git bash опцию, а не ограничить использование только из git bash. Это на другой странице установщика.

**Comment by kasper076** [comment]
Более тщательное гугление помогло чуток продвинуться. Причина предыдущей ошибки крылась в настройках безопасности.
![image](https://user-images.githubusercontent.com/11402408/103809484-9e72a100-506a-11eb-85c3-0ec40ea20ab8.png)
Выключил эту опцию.
Теперь картина изменилась
![image](https://user-images.githubusercontent.com/11402408/103809565-bfd38d00-506a-11eb-9bf5-493f6243c825.png)
Есть возможность это перевести? Копировать не дает. Может где-то файл с этими сообщениями есть?

**Comment by kasper076** [comment]
Создал новый репозиторий и все получилось. Большое спасибо.
