### ISSUE TITLE
Ошибка при разборе файла epf

### ISSUE THREAD

**Issue by stilet** [xDrivenDevelopment/precommit1c#22]
При втором коммите выскакивает сообщение что каталог в котором хранятся исходные коды уже существует и запрос - создать новый каталог в нем?. При положительном ответе формируется подкаталог с таким же именем.
Прикладываю скриншоты - понятнее будет.
![1](https://cloud.githubusercontent.com/assets/99677/6797357/fbd187fe-d211-11e4-9d21-fa13cc43da8f.png)
![2](https://cloud.githubusercontent.com/assets/99677/6797359/fe80f872-d211-11e4-9043-d1be85689d14.png)

**Comment by artbear** [comment]
На подобные проблемы никогда не нарывались :(
Дай больше информации.
1 Сабж брал из какой ветки - мастер/девелоп?
2 Покажи скриншот первого коммита - какие файлы в него вошли? как в него вошли файлы для PresteShopUNF_2014029.epf

**Comment by stilet** [comment]
Ветка develop. Зря конечно ее использовал. Вот скриншот первого коммита. Не понял с вопросом "как в него вошли". Где посмотреть?
![1](https://cloud.githubusercontent.com/assets/99677/6797775/23e3dff8-d217-11e4-93f5-c1aca695d0ca.png)

**Comment by stilet** [comment]
Получил еще раз develop ветку и вроде все заработало.

**Comment by artbear** [comment]
Ответы по первому коммиту получил.
Похоже, что все-таки есть проблемы при первом коммите
`fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.`

Провел эксперимент: Сделал пустой каталог, положил в него один epf, подготовил каталог .git\hooks, положив в него precommit1c (из девелоп)
и получил проблему - при первом коммите epf-файл не разбирается.
и та же ошибка `fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.`
```
F:\3>git init
Initialized empty Git repository in F:/3/.git/

F:\3>git add .


F:\3>git commit -m "init1"
Start hooks before commit for v8unpack erf and epf
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
INFO:root:A  "\320\227\320\260\320\277\320\270\321\201\321\214\320\232\320\222\321\200\320\260\321\207\321\203.epf"
INFO:root:?? xddGuidShow.epf
INFO:root:
[master (root-commit) 3f29256] init1
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 "\320\227\320\260\320\277\320\270\321\201\321\214\320\232\320\222\321\200\320\260\321\207\321\203.epf"
```

**Comment by artbear** [comment]
@pumbaEO Что скажешь ?
Опять проблема из #15

**Comment by zeratulayuris** [comment]
Давно исправлено.
