### ISSUE TITLE
Добавить ключ запуска, который позволит дополнительно сохранять mxl в текстовые файлы.

### ISSUE THREAD

**Issue by Pr-Mex** [xDrivenDevelopment/precommit1c#26]
Сейчас, когда происходит выгрузка данных макеты mxl просто остаются бинарями.
Предлагаю добавить опцию, ключ запуска, чтобы макеты сохранялись как текстовые файлы.
Тогда мы по-быстрому решим проблему того, что git не показывает нормально изменения в макетах, которые создают тестовые данные (fixtures).
Т.е. к самому mxl файлу добавиться ещё txt файл, который не будет участвовать потом при сборке из исходников. Но поможет гиту показывать что в макете изменилось.

**Comment by artbear** [comment]
Предлагаю формат YAML как наиболее читабельный в сравнении с json, xml, csv и т.п.

**Comment by Pr-Mex** [comment]
YAML надо программировать. А сконвертировать mxl в txt 1С умеет штатно. Это пара строк кода.

**Comment by artbear** [comment]
Согласен, для начала и простой текстовик подойдет.
Создал отдельную задачу #27 по Yaml

**Comment by bambr1975** [comment]
Pr-Mex, предложи вариант наименования такого ключа запуска

**Comment by artbear** [comment]
Мне нравится convert-mxl2txt или
mxl2txt

**Comment by Pr-Mex** [comment]
convert-mxl2txt вполне подходит
