### ISSUE TITLE
Ошибка во время выполнения сценария

### ISSUE THREAD

**Issue by alehinsasha** [xDrivenDevelopment/precommit1c#33]
**Имею**

Последнюю версию 1С:Предприятие 8.3 и новую версию vanessa-behavoir

**Делаю**

Открываю в 1С:Предприятие обработку vanessa-behavoir и в ней
1. Загружаю feature-файл
2. Генерирую с помощью обработки файл AdditionTest.epf
3. Жму кнопку "Перезагрузить" и получаю ошибку

**Получаю**

![2015-07-04_23-48-43](https://cloud.githubusercontent.com/assets/8247178/8509412/f77012d2-22a9-11e5-999c-2821d5ed2d7d.png)

Строка распаковки: python C:\Users\AlehinSasha\Documents\vanessa-behavoir\vendor\precommit1c\pyv8unpack.py  "C:\Users\AlehinSasha\Desktop\1\step_definitions\AdditionTest.epf" "C:\Users\AlehinSasha\Desktop\1\step_definitions\Src"

**Comment by allustin** [comment]
не совсем понял - это про что

**Comment by Pr-Mex** [comment]
Проблему подтверждаю.
Фишка в том, что в vanessa-behavoir использует Submoduls.
Т.е. Precommit подключен как сабмодуль.
В итоге что происходит:
программист скачивает себе проект vanessa-behavoir и в папке Vendor он получает каталог precommit1c. Но он не планирует ничего коммитить в vanessa-behavoir, поэтому в папку .git\hooks он ничего не копирует. В итоге при попытке использовать precommit из папеки Vendor фейлится, т.к. прекоммит требует файлов в папке hooks.

**Comment by artbear** [comment]
ИМХО это проблема использования precommit1c в проекте vanessa-behavoir.
Т.е. нужно правильно настроить окружение для использования в vanessa-behavoir

**Comment by Pr-Mex** [comment]
Ванесса тут не причём. Это проявится в любом проекте, который подключит прекоммит как сабмодуль. Требовать заполнения папки hooks, в то время как я просто србираюсь пользоваться прекоммитом через командную строку - неправильно.

**Comment by allustin** [comment]
@artbear это проблема именно precommit - дело в том что в нем жестко задачи пути https://github.com/xDrivenDevelopment/precommit1c/blob/8bf2e2a8dcdb9bac01c7c013479fa3a6e89842f6/pyv8unpack.py#L206

**Comment by allustin** [comment]
@artbear @Pr-Mex точнее не так.

precommit чётко ориентирован на работу с клиентским "хуками" git и не поддерживает вариант использования в виде простого распаковщика

**Comment by pumbaEO** [comment]
Исправил, ветка develop.
05 июля 2015 г. 12:19 пользователь "Alexey Lustin" <notifications@github.com>
написал:

**Comment by artbear** [comment]
Закрываю
