### ISSUE TITLE
Реализовать сборку исходников через oscript

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/precommit1c#38]

**Comment by EvilBeaver** [comment]
Артур, поясни, плиз суть данной задачи - что именно нужно сделать?

**Comment by artbear** [comment]
Вариант с Питоном умеет собирать внешние бинарники файлов 1С (епф) из исходных файлов.
Вариант 1Скрипт пока этого не умеет.

**Comment by nixel2007** [comment]
Есть успехи с реализацией данного пункта?
Могу попробовать подсобить с реализацией.

**Comment by EvilBeaver** [comment]
@nixel2007 подсоби, конечно :)

**Comment by nixel2007** [comment]
@EvilBeaver подумал, может есть уже какие-то начальные наработки, которые надо доделать.
я правильно понимаю, что для начала, грубо говоря, нужно взять исходник на питоне и оттранслировать его на 1script?

**Comment by EvilBeaver** [comment]
@nixel2007 существующий исходник на OS так и сделан. Взята логика с python-версии и в меру разумения перенесена на OS.
