### ISSUE TITLE
Ошибка декомпиляции обработок через 1script

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/precommit1c#39]
В текущем официальном инсталляторе OneScript отсутствует библиотека tempfiles, из-за чего v8files-extractor.os падает с ошибкой.
Решается ручным обновлением библиотек.

**Comment by EvilBeaver** [comment]
Это не баг, инсталлятор включает в себя не последнюю версию библиотек. Поэтому библиотеки и 1script живут в разных хранилищах и разрабатываются отдельно. С выпуском версии 1.0.11 в дистрибутив войдут свежие библиотеки

-----Исходное сообщение-----
От: "Nikita Gryzlov" <notifications@github.com>
Отправлено: ‎24.‎09.‎2015 21:54
Кому: "xDrivenDevelopment/precommit1c" <precommit1c@noreply.github.com>
Тема: [precommit1c] Ошибка декомпиляции обработок через 1script (#39)

В текущем официальном инсталляторе OneScript отсутствует библиотека tempfiles, из-за чего v8files-extractor.os падает с ошибкой.
Решается ручным обновлением библиотек.

**Comment by nixel2007** [comment]
Я не то чтобы считаю это багом... На мой взгляд стоит указать в документации к прекоммиту, какие дополнительные библиотеки надо доустановить в 1скрипт или какая версия библиотек нужна.

**Comment by nixel2007** [comment]
После выхода 1.0.11 уже неактуально.
