### ISSUE TITLE
Утилита не самодостаточна, нужна связь с v8unpack

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/precommit1c#46]
Утилита не самодостаточна, нужна связь с v8unpack (через переменную среды Path)

Нужно 
- или документировать нахождение v8unpack в Path
- или лучше положить утилиту как бинарник в проект
- или добавить submodule v8unpack от dmpas

@pumbaEO @allustin @EvilBeaver @nixel2007 Что выберем?

**Comment by nixel2007** [comment]
Требование нахождения в PATH - на мой взгляд крайне не удобно.
Про подмодуль - я правильно понимаю, что имеется в виду (эта)[https://github.com/dmpas/v8unpack] репа? В ней хранятся только сорцы, бинарники лежат вне репозитория на отдельном хранилище. Так что, на мой взгляд, подмодуль не поможет.

Добавить бинарник в проект кажется самым логичным в такой ситуации. Но надо контролировать, чтобы обработка v8Reader из подмодуля и бинарник для сбора файлов были одной версии (во избежание каких-либо артефактов).

**Comment by artbear** [comment]
Да, конечно, лучше бинарник положить.
Но я специально перечислил все возможные варианты для более полного анализа.

**Comment by artbear** [comment]
И лучше использовать одно имя бинарника, а не 2, как сейчас - v8unpack и unpackv8

**Comment by artbear** [comment]
[Положил утилиту v8unpack как бинарник в каталог tools](https://github.com/xDrivenDevelopment/precommit1c/commit/a086276a8c8c8d71165b1896b504b2c7d1e63d75)
@pumbaEO Проверь, пожалуйста, правки для Питона.

**Comment by artbear** [comment]
Повторюсь:
[Положил утилиту v8unpack как бинарник в каталог tools](https://github.com/xDrivenDevelopment/precommit1c/commit/a086276a8c8c8d71165b1896b504b2c7d1e63d75)
@pumbaEO Проверь, пожалуйста, правки для Питона.

**Comment by nixel2007** [comment]
@artbear для oscript-версии работает.
В рамках 2.0 можно закрывать.

**Comment by artbear** [comment]
@nixel2007 конечно, работает, я сам это реализовал :)
Закроем в рамках milestone `2.0.0-oscript-port` после принятия #72
