### ISSUE TITLE
Реализовать рекурсивную сборку файлов по указанному каталогу

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/precommit1c#48]
Сейчас и версия на питоне и версия на oscript умеет собирать обработки только из одного указанного в параметре каталога. 
Предлагаю в команду --compile добавить параметр-флаг --recursive, который будет рекурсивно обходить каталоги. Для каталогов, в которых он найдёт файл renames.txt, будет запускаться сборка файлов с раскладыванием полученных бинарных файлов в той же иерархии, что и каталоги исходников. 
Тут сразу есть проблема - по содержанию каталога я не могу автоматически понять, отчет передо мной или обработка. Возможно ли эту информацию получить из какого-то служебного файла? 
В силу знаний, свою реализацию могу предоставить только на oscript.

**Comment by artbear** [comment]
Мы постепенно переходим на оскрипт, так что интересует реализация на нем.

Issue полезна

вт, 3 Ноя 2015, 23:11, Nikita Gryzlov <notifications@github.com>:

**Comment by EvilBeaver** [comment]
Да, знание про отчет/обработку есть внутри, я вспомню где именно

-----Исходное сообщение-----
От: "Nikita Gryzlov" <notifications@github.com>
Отправлено: ‎03.‎11.‎2015 23:11
Кому: "xDrivenDevelopment/precommit1c" <precommit1c@noreply.github.com>
Тема: [precommit1c] Реализовать рекурсивную сборку файлов по указанному каталогу (#48)

Сейчас и версия на питоне и версия на oscript умеет собирать обработки только из одного указанного в параметре каталога. 
Предлагаю в команду --compile добавить параметр-флаг --recursive, который будет рекурсивно обходить каталоги. Для каталогов, в которых он найдёт файл renames.txt, будет запускаться сборка файлов с раскладыванием полученных бинарных файлов в той же иерархии, что и каталоги исходников. 
Тут сразу есть проблема - по содержанию каталога я не могу автоматически понять, отчет передо мной или обработка. Возможно ли эту информацию получить из какого-то служебного файла? 
В силу знаний, свою реализацию могу предоставить только на oscript.

**Comment by nixel2007** [comment]
Начал работать над задачей.
