### ISSUE TITLE
При сборе файлов определять тип файла автоматически

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/precommit1c#51]
Сейчас при компиляции (режим --compile) отчетов и обработок из исходников необходимо явно указывать тип собираемого файла - epf/erf.
Такое требование делает невозможным сценарий хранения в одной папке и отчетов и обработок и сбора их единой командной с флагом --recursive.

По словам @EvilBeaver, по содержанию каталога исходных кодов можно понять отчет перед нами или обработка. 
Необходимо реализовать это определение при сборе файлов и отказаться от использования параметра --type вообще.

Пока заметил, что в строке 10 у файлов-описаний отчетов параметров-гуидов больше, чем в этой же строке у обработок. Вероятно это гуиды форм отчетов/настроек/вариантов, тогда как у обработки есть только форма самой обработки.

**Comment by artbear** [comment]
@awa15 У тебя случайно нет информации, как узнать тип внешнего файла?

**Comment by awa15** [comment]
@artbear Я не знаю, как вы раскладываете файлы и куда у вас смотреть, я расскажу, как это узнать в собранном файле.
Итак, есть файл root, в котором указан ИД метаданных. Например,
```
{2,1689faa2-afd1-433f-8f61-aab5ad823f52,}
```
В нашем примере этот ИД 1689faa2-afd1-433f-8f61-aab5ad823f52
Смотрим файл с таким именем - это корневой контейнер. В нашем примере это будет как-то так
```
{1,
{1689faa2-afd1-433f-8f61-aab5ad823f52},1,
{c3831ec8-d8d5-4f93-8a22-f9bfae07327f,
{1,
{4,7706b638-a5e7-4610-b490-fea137605486,f768a858-8274-4902-b812-79ab25866b1b,
{0,
... и т.д.
```
Первый УИД - это тот же самый ИД метаданных, а вот второй УИД - это тип внешнего файла. c3831ec8-d8d5-4f93-8a22-f9bfae07327f - это внешняя обработка, e41aff26-25cf-4bb6-b6c1-3f478a75f374 - это внешний отчет.
Если встретите что-то другое, обязательно дайте мне знать! 
Надеюсь, этой информации вам будет достаточно для заявленной цели.

**Comment by nixel2007** [comment]
@awa15 Валерий, спасибо большое, то, что нужно!

**Comment by EvilBeaver** [comment]
@awa15 спасибо!

Ну и да, я говорил, что можно поискать в V8 Reader, вот пруфлинк:

https://sourceforge.net/p/v8reader/code/101/tree//trunk/v8viewer/core/V8MetadataContainer.cs#l17
