### ISSUE TITLE
Ошибка сбора/разбора отчета

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/precommit1c#56]
Несколько моих отчетов после разбора на исходники обратно собираются в невалидную erf (ошибка формата потока).
Пример отчета (ссылка на личный g-drive): https://drive.google.com/file/d/0BzrHpvxfLxBiUzJyUU9wbWs2djQ/view?usp=sharing

Разбирается в исходники:
https://drive.google.com/file/d/0BzrHpvxfLxBiczRmWDQzeXBhZUU/view?usp=sharing

Собираемый файл (битый):
https://drive.google.com/file/d/0BzrHpvxfLxBiZGhOZkQzX1dxWTQ/view?usp=sharing

Разбор проводится командной: 
`oscript -encoding=utf-8 libs/precommit1c/v8files-extractor.os --git-precommit "source"`

Сборка:
`oscript -encoding=utf-8 libs/precommit1c/v8files-extractor.os --compile "source/processings" "processings" --recursive`

Используется последняя develop-версия precommit1c - 89a06aea157bd2b7cacf97197138af33c25b4c9e

@artbear, @awa15, можете что-нибудь подсказать? 

Платформа 8.3.7.1759. Вечером могу попробовать собрать на 8.3.6

P.S. Тесты в девелоп опять падают

**Comment by nixel2007** [comment]
Вывод лога с включенной отладкой
```
D:\git\bit_vuz>oscript -encoding=utf-8 libs/precommit1c/v8files-extractor.os --git-precommit "source"
ОТЛАДКА - ТипЗнч(Аргументы)= Структура
ОТЛАДКА - Передана команда: --git-precommit
ОТЛАДКА - --remove-orig-bin-files = Да
ОТЛАДКА - ВыходнойКаталог = source
ОТЛАДКА - Текущий каталог D:\git\bit_vuz
ОТЛАДКА - Каталог выгрузки source
ОТЛАДКА - Выполняю команду git config --local core.quotepath
ОТЛАДКА -       Код возврата 0
ОТЛАДКА -       Вывод команды <false>
ОТЛАДКА - Запускаю git diff-index --name-status --cached HEAD
ОТЛАДКА -       Вывод команды гит: A    processings/[Приемная комиссия]/[Отчеты]/СводкаПоЛичнымДелам.erf

ОТЛАДКА - ЖурналИзмененийГит:
ОТЛАДКА -       <A      processings/[Приемная комиссия]/[Отчеты]/СводкаПоЛичнымДелам.erf>
ОТЛАДКА -               В журнале git найдено имя файла <processings/[Приемная комиссия]/[Отчеты]/СводкаПоЛичнымДелам.erf>
ОТЛАДКА -       <>
ОТЛАДКА - Изучаю файл из журнала git processings/[Приемная комиссия]/[Отчеты]/СводкаПоЛичнымДелам.erf
ОТЛАДКА - Получен из журнала git файл processings/[Приемная комиссия]/[Отчеты]/СводкаПоЛичнымДелам.erf
ИНФОРМАЦИЯ - Проверка необходимости выгрузки файла D:\git\bit_vuz\processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам.erf в каталог D:\git\bit_vuz\source, корень D:\git\bit_vuz
ОТЛАДКА - ОтносительныйПутьКаталогаФайла <processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам>
ОТЛАДКА - ПутьКаталогаИсходников <D:\git\bit_vuz\source\processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам>
ОТЛАДКА - Очищаем каталог D:\git\bit_vuz\source\processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам
ОТЛАДКА - Запускаем распаковку файла
ОТЛАДКА - КлючСоединенияСБазой /F"C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\v8r_TempDB"
ОТЛАДКА - ИмяПользователя <>
ОТЛАДКА - Путь к V8Reader: D:\git\bit_vuz\libs\precommit1c\v8Reader\V8Reader.epf
ОТЛАДКА - Командная строка V8Reader: /C"decompile;pathtocf;D:\git\bit_vuz\processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам.erf;pathout;D:\git\bit_vuz\source\processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам;convert-mxl2txt;ЗавершитьРаботуПосле;"
ОТЛАДКА - Проверяю равенство КлючСоединенияСБазой() = КлючВременногоКонтекста() и Не ВременнаяБазаСуществует()
ОТЛАДКА - КлючСоединенияСБазой() /F"C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\v8r_TempDB"
ОТЛАДКА - КлючВременногоКонтекста() /F"C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\v8r_TempDB"
ОТЛАДКА - ВременнаяБазаСуществует() Нет
ОТЛАДКА - Равенство выполняется.
ОТЛАДКА - Создаю временную базу. Путь C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\v8r_TempDB
ОТЛАДКА - Создаю файловую базу C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\v8r_TempDB
ОТЛАДКА - "C:\Program Files (x86)\1cv8\8.3.7.1759\bin\1cv8.exe" CREATEINFOBASE File="C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\v8r_TempDB" /Out"C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\log.txt"
ОТЛАДКА - файл информации:
Создание информационной базы ("File="C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\v8r_TempDB";Locale = "ru_RU";") успешно завершено

ОТЛАДКА - Удаляю файл информации 1С
ОТЛАДКА - "C:\Program Files (x86)\1cv8\8.3.7.1759\bin\1cv8.exe" ENTERPRISE /F"C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\v8r_TempDB" /Out"C:\Users\na_gryzlov\AppData\Local\Temp\k5j3eqp2.yg1.tmp\log.txt" /WA+ /DisableStartupMessages /DisableStartupDialogs /RunModeOrdinaryApplication /Execute "D:\git\bit_vuz\libs\precommit1c\v8Reader\V8Reader.epf" /C"decompile;pathtocf;D:\git\bit_vuz\processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам.erf;pathout;D:\git\bit_vuz\source\processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам;convert-mxl2txt;ЗавершитьРаботуПосле;"
ОТЛАДКА - файл информации:

ОТЛАДКА - Код возврата равен 0
ОТЛАДКА - Вывод 1С:Предприятия -
ОТЛАДКА - Очищаем каталог временной ИБ
ИНФОРМАЦИЯ - Завершена проверка необходимости выгрузки файла D:\git\bit_vuz\processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам.erf в каталог D:\git\bit_vuz\source, корень D:\git\bit_vuz

ОТЛАДКА - Запуск git add для каталога D:\git\bit_vuz\source\processings\[Приемная комиссия]\[Отчеты]\СводкаПоЛичнымДелам
ОТЛАДКА - Вывод git add:

```

**Comment by artbear** [comment]
@nixel2007 Сегодня время вряд ли найду, возможно, завтра смогу посмотреть.
Отчеты пока ни разу не собирал

Попробуй собрать и снова разобрать, далее сравнить старые исходники и полученные новые.
Какие файлы и чем отличаются?

**Comment by nixel2007** [comment]
@artbear что удивительно, большая часть отчетов собирается нормально. 
Повторно разобрать не могу - при разборе в 1с выскакивает ошибка разбора хмл

**Comment by artbear** [comment]
>Повторно разобрать не могу - при разборе в 1с выскакивает ошибка разбора хмл

При запуске V8Reader ?
Попробуй собрать через сабж, а разобрать через v8unpack
исходную обработку также разбери через v8unpack и сравни полученные исходники.

**Comment by awa15** [comment]
Проблема с файлом формы.
В renames.txt есть такая строка
```
c7d19eff-51b1-4a1d-bcb7-25fad375faaf.0-->Form\ФормаОтчета\Форма.txt
```
Однако, одновременно есть и файл c7d19eff-51b1-4a1d-bcb7-25fad375faaf.0 в папке und, и файл Form\ФормаОтчета\Форма.txt, но пустой (только три байта BOM UTF8). При обратной сборке файл c7d19eff-51b1-4a1d-bcb7-25fad375faaf.0 заменяется пустым из Form\ФормаОтчета\Форма.txt.

**Comment by nixel2007** [comment]
@awa15 посмотрел форму - у нее пустой модуль. Поэтому и файл пустой.

**Comment by nixel2007** [comment]
Если смотреть содержание дальше:
```
e7243ad7-fa0a-4247-a6c1-97471aba7640.0-->Макеты\ОсновнаяСхемаКомпоновкиДанных\T.xml
e7243ad7-fa0a-4247-a6c1-97471aba7640.0-->und\e7243ad7-fa0a-4247-a6c1-97471aba7640.0
```
Только здесь сначала заменяется XML, а потом уже und поверх.

Я правильно понимаю, что это проблема самого распаковщика v8reader (часть с renames и распределением по папкам)?

**Comment by awa15** [comment]
@nixel2007 К сожалению, я понятия не имею, как работает precommit1C, и кто формирует файл renames.txt.
Я просто сравнил по файлам твою исходную обработку и битый результат - отличие в файле c7d19eff-51b1-4a1d-bcb7-25fad375faaf.0, в исходном виде он заполненный (и совпадает с und\c7d19eff-51b1-4a1d-bcb7-25fad375faaf.0 в разборе), а в битой - пустой (и совпадает с Form\ФормаОтчета\Форма.txt). Сорри, кроме этого факта ничем помочь не могу))

**Comment by bambr1975** [comment]
файл renames.txt формирует v8reader. Надо исправлять - @nixel2007, спасибо, что протестировал. вообще странно, что про ты спрашиваешь @awa15 и @artbear . У V8reader-а пока что только два реальных автора - я и @pumbaEO - остальные только идеями помогали))) Конкретно эта проблема связана с тем, что я этот кусок вообще не тестировала)))

**Comment by nixel2007** [comment]
@awa15 Спасибо! Главное, локализовать проблему :)

@artbear на сколько я понимаю, по обработка v8reader при формировании renames.txt и/или в момент вырезания кода модуля может *внезапно* поменять порядок строк. Обычно порядок такой:
```
37d35857-26d5-420f-a7bc-d700c0cfc351.0-->Form\ПоискДублей\Форма.txt
37d35857-26d5-420f-a7bc-d700c0cfc351.0-->und\37d35857-26d5-420f-a7bc-d700c0cfc351.0
```
т.е. сначала идет красиво вырезанный файл Форма.txt, а иногда ситуация такая:
```
4e79011d-e674-4b01-8868-2e3f0a598368.0-->und\4e79011d-e674-4b01-8868-2e3f0a598368.0
4e79011d-e674-4b01-8868-2e3f0a598368.0-->Form\ОбластьПоискаДублей\Форма.txt
```
когда сначала идет полный файл в und, а потом уже красиво вырезанный кусок с текстом модуля.

В принципе, этим можно рулить на уровне v8files-extractor (подозреваю, что при сборе через python-версию, эта ошибка повторится)

**Comment by nixel2007** [comment]
@bambr1975 Здравствуй! :) ну... я с кем общался в рамках этого репо, у того и спросил :) Рад, что узнал, кто авторы :D

**Comment by EvilBeaver** [comment]
@bambr1975 какие люди! Привет!
Ну у awa, понятное дело, почему спрашивают, он в курсе структур данных. А тебя в наши беседы не заманишь же :smile:

**Comment by artbear** [comment]
@EvilBeaver вини меня, я любого заманю :)

**Comment by artbear** [comment]
@bambr1975 
>У V8reader-а пока что только два реальных автора - я и @pumbaEO - остальные только идеями помогали))) 

А как же я ? у меня целых 9 коммитов :)

**Comment by bambr1975** [comment]
@nixel2007 вроде исправлено. Не посмотрите https://github.com/xDrivenDevelopment/v8Reader/tree/develop ?

**Comment by nixel2007** [comment]
@bambr1975 да, пропали и строки с "красивыми" именами и дубли строк und.
А возможно ли оставить "красивые" файлы в renames, но гарантировано помещать их на первое место? Или вообще писать их в отдельный файл.
Use case: при необходимости откорректировать обработку прямо в исходниках залезаем в renames/новый файл и видим, что модуль формы - это und/такой-то. И там уже правим (+ в "красивом" файле, для наглядности)

**Comment by artbear** [comment]
@pumbaEO посмотришь https://github.com/xDrivenDevelopment/precommit1c/issues/56#issuecomment-157495251 ?

**Comment by artbear** [comment]
@bambr1975 @pumbaEO что-то удалось посмотреть/решить по сабжу https://github.com/xDrivenDevelopment/precommit1c/issues/56#issuecomment-157495251 ?

**Comment by bambr1975** [comment]
Мне больше по душе отдельный файл для соответствия "красивым именам". Прошу совета относительно того, как он должен называться и какие конкретно данные туда должны писаться

**Comment by nixel2007** [comment]
@bambr1975 для моих целей будет достаточно точно такой же строки
```
4e79011d-e674-4b01-8868-2e3f0a598368.0-->Form\ОбластьПоискаДублей\Форма.txt
```
Для справки еще можно добавить номер строки "С" и "По", из которых был скопирован этот кусок текста (для модулей)

**Comment by bambr1975** [comment]
@nixel2007 название для файла "красивых" переименований придумай, плиз

**Comment by nixel2007** [comment]
@bambr1975 самое сложное в работе программиста - придумывать имена переменных, да? :D 
Есть несколько вариантов, в зависимости от того, что туда будет помещаться.

Если в файл будут класться **только** вырезаемые части других файлов, то есть по сути именно *части* информации, которая дублируется, то: cut_out.txt или dublicated_names.txt

Если туда будут падать любые "красивые" переименования, то... <s>sweet_shiny_wow_dogenames.txt</s> reducted_names.txt, например.

**Comment by awa15** [comment]
@bambr1975 @nixel2007 Обзовите типа maps.txt и не парьтесь))

**Comment by nixel2007** [comment]
@bambr1975 @awa15 на текущем проекте популярным стало слово "мэппинг". уже регистров 10 с таким словом в названии)))

**Comment by awa15** [comment]
@nixel2007 Если оно так и написано, не "mapping", а "мэппинг", то, имхо, это ужасно)) Есть же отличные русские слова "соответствие" или "отображение".

**Comment by EvilBeaver** [comment]
@nixel2007 а что такое **redacted**_names??

**Comment by nixel2007** [comment]
@EvilBeaver отредактированные/скорректированные имена? Были непонятные числа с буквами, стали человеко-читаемые Form\ОбластьПоискаДублей\Форма.txt

**Comment by bambr1975** [comment]
@nixel2007 https://github.com/xDrivenDevelopment/v8Reader/tree/develop Вроде готово.

**Comment by nixel2007** [comment]
@bambr1975 выглядит здорово :) думаю, последний штрих - нужно ли создавать maps.txt с пустым содержанием (вопрос скорее идеологический)? сейчас такой пустой файл создается.
