### ISSUE TITLE
Ошибка при выполнении первого коммита

### ISSUE THREAD

**Issue by IslamA** [xDrivenDevelopment/precommit1c#61]
Выполнял все действия согласно описанию в файле README.md.
На шаге из описания:

>После установки достаточно для проверки сделать commit для любого файла epf/erf, и в вашем репозитории автоматически должна создаться папка *src*, полностью повторяющая структуру проекта, изменённые или добавленные файлы распакуются в папки с аналогичными наименованиями..<

получаю ошибку,
`<ОШИБКА - {Модуль [ПутьКМоемуРепозитарию]\.git\hooks\v8files-extractor.os / Ошибка в строке: 107 / Метод объекта не обнаружен (ДобавитьПараметрФлагКоманды)}`

**Comment by nixel2007** [comment]
@IslamA обновите библиотеки osrcipt-library

**Comment by nixel2007** [comment]
@EvilBeaver dependency hell, here we come

**Comment by EvilBeaver** [comment]
@nixel2007 ну кто бы спорил, что version hell не заставит себя ждать. Но не могу же я один обеспечить его отсутствие. Например, когда в precommit появилась зависимость от метода ДобавитьПараметрФлаг можно было добавить контроль нужной версии библиотеки. Но эта версия нигде не хранится, значит нужно еще и эту инфраструктуру как-то обеспечить.

Короче, проблема ждет своих решателей. На то он и open source. Я буду крайне признателен за любую помощь кодом или идеями.

**Comment by artbear** [comment]
А я ведь в свое время писал о необходимости ввода версий для библиотек, но
вы меня не поддержали

вт, 19 Янв 2016, 21:33, Andrei Ovsiankin <notifications@github.com>:

**Comment by nixel2007** [comment]
@artbear так все за. просто пока не придумано хорошего единого алгоритма.
Вот оно даже обсуждение этого добра https://github.com/EvilBeaver/oscript-library/issues/34

**Comment by nixel2007** [comment]
@IslamA получилось решить проблему?

**Comment by IslamA** [comment]
@nixel2007 с ветки девелоп как вы и рекомендовали получил последние изменения. 
Проблема разрешилась, спасибо.
