### ISSUE TITLE
Ошибка при работе с OneScript

### ISSUE THREAD

**Issue by stilet** [xDrivenDevelopment/precommit1c#62]
При использовании стабильной версии OneScript при первом коммите выдает ошибку:
Start hooks before commit for v8unpack erf and epf
**ОШИБКА - {Модуль D:\proj\dmitrov\ex-xml\.git\hooks\v8files-extractor.os / Ошибка                                                                                                                           в строке: 107 / Метод объекта не обнаружен (ДобавитьПараметрФлагКоманды)}**

При использовании develop версии не коммитит с сообщением:
Start hooks before commit for v8unpack erf and epf
ОТЛАДКА - Добавляю позиционный параметр ПутьВходящихДанных
ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
ОТЛАДКА - Добавляю параметр-флаг --remove-orig-bin-files
ОТЛАДКА - Добавляю позиционный параметр ПутьВходящихДанных
ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
ОТЛАДКА - Добавляю параметр-флаг --recursive
ОТЛАДКА - Разбор команды: --git-precommit
ОТЛАДКА - Попадаю в РазобратьАргументы
ОТЛАДКА - Сбрасываю параметр-флаг: --remove-orig-bin-files
ОТЛАДКА - Выбран токен: src
ОТЛАДКА - Ищу именованный параметр src
ОТЛАДКА - Ищу параметр-флаг src
ОТЛАДКА - Установлено значение позиционного параметра <ВыходнойКаталог = src>
ОТЛАДКА - Выбран токен:
ОТЛАДКА - Закончились токены
ОТЛАДКА - Трассировка РезультатРазбора:
ОТЛАДКА -               --remove-orig-bin-files:Нет
ОТЛАДКА -               ВыходнойКаталог:src
ОТЛАДКА - Трассировка РезультатКоманды.ЗначенияПараметров:
ОТЛАДКА -               --remove-orig-bin-files:Нет
ОТЛАДКА -               ВыходнойКаталог:src
ОТЛАДКА - ТипЗнч(Аргументы)= Структура
ОТЛАДКА - Передана команда: --git-precommit
ОТЛАДКА - --remove-orig-bin-files = Нет
ОТЛАДКА - ВыходнойКаталог = src
ОТЛАДКА - Текущий каталог D:\proj\dmitrov\ex-xml
ОТЛАДКА - Каталог выгрузки src
ОТЛАДКА - Выполняю команду git config --local core.quotepath
ОТЛАДКА - cmd /C "git config --local core.quotepath > "C:\Users\Leo\AppData\Local\Temp\2w1x3cf3.t1t.tmp" 2>&1"
ОТЛАДКА - Код возврата: 0
ОТЛАДКА -       Код возврата 0
ОТЛАДКА -       Вывод команды <false>
ОТЛАДКА - Запускаю git diff-index --name-status --cached HEAD
ОТЛАДКА - cmd /C "git diff-index --name-status --cached HEAD > "C:\Users\Leo\AppData\Local\Temp\1hss2f0p.npg.tmp" 2>&1"
ОТЛАДКА - Код возврата: 128
ОТЛАДКА -       Вывод команды гит: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

ОТЛАДКА - Запускаю git status --porcelain
ОТЛАДКА - cmd /C "git status --porcelain > "C:\Users\Leo\AppData\Local\Temp\41mwsavl.0iy.tmp" 2>&1"
ОТЛАДКА - Код возврата: 0
ОТЛАДКА -       Вывод команды гит: A  ВыгрузкаДиалог.epf

ОТЛАДКА - ЖурналИзмененийГит:
ОТЛАДКА -       <A  ВыгрузкаДиалог.epf>
ОТЛАДКА -               В журнале git найдено имя файла <ВыгрузкаДиалог.epf>
ОТЛАДКА -       <>
ОТЛАДКА - Изучаю файл из журнала git ВыгрузкаДиалог.epf
ОТЛАДКА - Получен из журнала git файл ВыгрузкаДиалог.epf
ИНФОРМАЦИЯ - Проверка необходимости выгрузки файла D:\proj\dmitrov\ex-xml\ВыгрузкаДиалог.epf в каталог D:\proj\dmitrov\ex-xml\src, корень D:\proj\dmitrov\ex-xml
ОТЛАДКА - ОтносительныйПутьКаталогаФайла <ВыгрузкаДиалог>
ОТЛАДКА - ПутьКаталогаИсходников <D:\proj\dmitrov\ex-xml\src\ВыгрузкаДиалог>
ОТЛАДКА - Создаем новый каталог D:\proj\dmitrov\ex-xml\src\ВыгрузкаДиалог
ОТЛАДКА - Запускаем распаковку файла
ОТЛАДКА - КлючСоединенияСБазой /F"C:\Users\Leo\AppData\Local\Temp\c13nln0f.jqn.tmp\v8r_TempDB"
ОТЛАДКА - ИмяПользователя <>
ОТЛАДКА - Путь к V8Reader: D:\proj\dmitrov\ex-xml\.git\hooks\v8Reader\V8Reader.epf
**ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os / Ошибка в строке: 276 / [Failed] Ожидали, что проверяемое значение (Ложь) является ИСТИНОЙ.}**

**Comment by nixel2007** [comment]
Обновите библиотеки oscript-library с дев-версии.

**Comment by stilet** [comment]
Обновил. То же самое

**Comment by nixel2007** [comment]
submodules инициализировали?

`git submodules update --init --recursive`

**Comment by stilet** [comment]
git submodules update --init --recursive
git: 'submodules' is not a git command. See 'git --help'.

Did you mean this?
        submodule

**Comment by nixel2007** [comment]
упс. да,
`git submodule update --init --recursive`

**Comment by stilet** [comment]
нужен какой то модуль для git?

**Comment by nixel2007** [comment]
Не совсем. Именно для работы precommit1c нужен внешний репозиторий v8reader, который к нему залинкован через [подмодули](https://git-scm.com/book/ru/v1/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%9F%D0%BE%D0%B4%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D0%B8).

**Comment by stilet** [comment]
команду выполнил - прошла нормально. Заменил библиотеки в C:\Program Files (x86)\OneScript\lib из git но ошибка не ушла

**Comment by nixel2007** [comment]
Выполните повторно пункт установки
` Наконец, содержимое каталога необходимо скопировать в каталог .git/hooks/ вашего проекта. `

**Comment by stilet** [comment]
на всякий пожарный опишу действия - скопировал из папки D:\proj\oscript-library\src полученной с github все папки и файлы в папку C:\Program Files (x86)\OneScript\lib где проинсталированн по умолчанию OneScript

**Comment by stilet** [comment]
нет, не срабатывает. Вообще удалил репозитарий и снова закачал, потом скопировал заново. А где эта обработка сам файл v8unpack.exe ищет? Мне кажется дело в нем

**Comment by nixel2007** [comment]
Ошибка все та же:
```
ОШИБКА - {Модуль D:\proj\dmitrov\ex-xml.git\hooks\v8files-extractor.os / Ошибка в строке: 107 / Метод объекта не обнаружен (ДобавитьПараметрФлагКоманды)}
```
?

**Comment by nixel2007** [comment]
> А где эта обработка сам файл v8unpack.exe ищет? Мне кажется дело в нем
файл ищется в каталоге tools, который тоже должен быть в хуках.

**Comment by stilet** [comment]
Да. Блин нет в каталоге D:\proj\precommit1c\v8Reader ничего. пустой.

**Comment by nixel2007** [comment]
так. еще раз по пунктам.
* скачали репо прекоммит1с
* открыли консоль в папке репо прекоммит1с
* выполнили git submodule update --init --recursive
* выполнили `copy-to-hook.cmd`

**Comment by stilet** [comment]
заработало. Наверное имеет смысл немного поправить README.md, чтобы юнные падаваны не возились с ошибками

**Comment by nixel2007** [comment]
Да, пометил задачку. Спасибо!

https://github.com/xDrivenDevelopment/precommit1c/issues/63

**Comment by stilet** [comment]
Вам спасибо!

**Comment by nixel2007** [comment]
@artbear можно закрыть.
