### ISSUE TITLE
Лицензирование

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/precommit1c#67]
Вопрос больной, но надо решить. 

Текущие результаты голосования:
artbear - Apache
EvilBeaver - Apache (возможна MPL)
pumbaEO - Apache
allustin - Apache (возможна BSD)
nixel2007 - Apache (возможна MIT)
Cujoko - воздержался
Infactum - Apache (возможны BSD и MIT)
karnilaev - Apache

**Comment by nixel2007** [comment]
@EvilBeaver высказался за мозиллу или апачу. В целом по xdd вроде превалирует апач

**Comment by artbear** [comment]
Я за любой вариант.

Тут другая проблема: тот же товарищ Лустин говорит о лицензиях, а сам очень не любит прописывать чужие лицензии в своем коде, как положено согласно лицензии. 
Ярчайший пример - использование кода и решений xUnitFor1C в продуктах SB
Например, https://github.com/silverbulleters/vanessa-behavior/issues/54 или https://github.com/silverbulleters/vanessa-behavior/pull/83

**Comment by nixel2007** [comment]
Как бы не поступал "товарищ Лустин", это не отменяет того факта, что в precommit1c сейчас вообще не указана лицензия.

----- Ответное сообщение -----
От: "Artur Ayukhanov" <notifications@github.com>
Кому: "xDrivenDevelopment/precommit1c" <precommit1c@noreply.github.com>
Копия: "Nikita Gryzlov" <nixel2007@gmail.com>
Тема: [precommit1c] Лицензирование (#67)
Дата: вт, янв. 26, 2016 09:29

Я за любой вариант.

Тут другая проблема: тот же товарищ Лустин говорит о лицензиях, а сам очень не любит прописывать чужие лицензии в своем коде, как положено согласно лицензии. 

Ярчайший пример - использование кода и решений xUnitFor1C в продуктах SB

Например, silverbulleters/vanessa-behavior#54 или silverbulleters/vanessa-behavior#83

&mdash;

**Comment by artbear** [comment]
@pumbaEO Ты за какую лицензию?

@kuntashov @nixel2007 @EvilBeaver  Напомните вкратце разницу между мозиллой и апачем?

**Comment by nixel2007** [comment]
@artbear если совсем вкратце - мпл копилефтная, апач разрешительная :) 
http://m.habrahabr.ru/post/243091

**Comment by artbear** [comment]
Ждем @pumbaEO как автора идеи.

**Comment by g-ones** [comment]
@nixel2007 @artbear когда лицензия устанавливается "потом" - надо спрашивать всех контрибьюторов https://github.com/xDrivenDevelopment/precommit1c/graphs/contributors

просто провести голосование в римском стиле и всё.

а на будущее - сразу ставьте лицензию и ссылку на GitHub CLA

**Comment by pumbaEO** [comment]
Я за апач.

2016-01-26 10:23 GMT+03:00 Artur Ayukhanov <notifications@github.com>:

> Ждем @pumbaEO <https://github.com/pumbaEO> как автора идеи.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/precommit1c/issues/67#issuecomment-174868676>
> .
>



-- 
З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by allustin** [comment]
@artbear а товарищ Лустин не любит когда каким то странным образом его фамилия исчезает из лицензии ;-)

а за Apache как все, хотя BSD мне нравится больше

**Comment by nixel2007** [comment]
я за апач.

Из контрибьюторов остались:
@artbear 
@EvilBeaver 
@Cujoko 
@Infactum
@karnilaev

Ребята, выскажитесь по поводу применяемой лицензии, пожалуйста. Либо явно, либо "воздержусь"

**Comment by artbear** [comment]
Лады, я за апач

**Comment by EvilBeaver** [comment]
Апач

**Comment by nixel2007** [comment]
@g-ones позволь поинтересоваться :)
голосование в римском стиле - это по принципу большинства или когда все приняли единогласное решение (за исключением воздержавшихся)?

Никогда не слышал такой фразы просто)

offtopic. подсказали еще вот такой вариант :D
> мб, по спорному вопросу, собирают по числу вариантов ответов гладиаторов.
каждый гладиатор тащит жребий, какой ответ он будет представлять.
люди, которые склонны к тому, или иному ответу, делают ставки на этот ответ (тут спорно - до жребия ответов между гладиаторами, или после).
собирается банк ставок, происходит бой.
побеждает гладиатор, и ответ, который он представляет - считается правильным.
банк делится между сделавшими ставки на этот ответ, за удержанием процента комиссионных, за организацию боев.

**Comment by g-ones** [comment]
@EvilBeaver виноват - надо было сразу ссылки скинуть

http://www.conferencesthatwork.com/index.php/presentations/2012/06/the-right-way-to-vote-part-1/
http://www.conferencesthatwork.com/index.php/event-design/2012/06/testing-consensus-using-roman-voting/

мне кто-то говорил на конференции что такое использовали ребята из io.js для достижения консенсуса

:thumbsdown:
:thumbsup:

**Comment by EvilBeaver** [comment]
@g-ones я чой-та не уловил. А в чем именно я виноват?

**Comment by nixel2007** [comment]
@EvilBeaver вероятно, что @g-ones во-первых, имел ввиду меня, а во-вторых, забыл запятую при обращении)

**Comment by EvilBeaver** [comment]
@nixel2007 :laughing:  вот уж, действительно, "казнить нельзя помиловать" ))))

**Comment by g-ones** [comment]
@nixel2007 @nixel2007 виноват **Я** - надо было сразу после фразы "в римском стиле" скинуть ссылки на то где я эту информацию прочитал

**Comment by Infactum** [comment]
Уж не знаю как я попал в это голосование, но в целом против apache ничего не имею. Хотя как и @allustin мне больше симпатизирует MIT(BSD).

**Comment by nixel2007** [comment]
@Infactum у тебя есть один коммит здесь :)

**Comment by karnilaev** [comment]
Апач

**Comment by nixel2007** [comment]
Таким образом, все невоздершавшиеся контрибьюторы высказались за Apache. 
Думаю, можно оформлять.

**Comment by nixel2007** [comment]
Есть странное предложение.
Раз юридически xDrivenDevelopment не существует, то может указать как владельца @pumbaEO ?
с указанием авторов и дополнительной ссылкой на xDD в NOTICE?

**Comment by nixel2007** [comment]
Пингану.
Особенно интересует мнение @pumbaEO, @artbear, @EvilBeaver, @allustin

**Comment by pumbaEO** [comment]
я не против "то может указать как владельца @pumbaEO (как первоначального автора и идеолога)?" :) 
:+1:

**Comment by EvilBeaver** [comment]
Я не застал начала проекта precommit. Если Женя изначальный автор - то разумеется, я не против. Если старожилы помнят кого-то еще - надо привлечь его к беседе.

**Comment by nixel2007** [comment]
> Если старожилы помнят кого-то еще - надо привлечь его к беседе.

Я вроде бы сюда призывал всех контрибьюторов с репозитория.

**Comment by EvilBeaver** [comment]
Тогда за чем дело стало?

**Comment by nixel2007** [comment]
@EvilBeaver жду реакции @artbear как "большого" контрибьютора прекоммита и @allustin как основное заинтересованное в корректной лицензии лицо

**Comment by allustin** [comment]
Я выше высказался на Apache.

**Comment by nixel2007** [comment]
@allustin то, что Апач-то все решили. Нормально ли с точки зрения СБ указание Жени как владельца продукта?

**Comment by nixel2007** [comment]
Нельзя не упомянуть @bambr1975. Пожалуйста, выскажи свое мнение по вопросу :)

**Comment by bambr1975** [comment]
Скрипт разложения на папки исходников - идея и реализация @pumbaEO . Все правильно.

**Comment by artbear** [comment]
Я лично за лицензию Апач
но против выделения отдельного владельца.
Данный продукт вырос в составе нашего сообщества xdd, активно дорабатывался именно в составе xdd и нельзя этот факт не учитывать.

Первоначальная идея, конечно, @pumbaEO

**Comment by allustin** [comment]
@nixel2007 не увидел вопроса. Значит кейс на сегодня (апрель) следующий - мы научились проходить СБ в госучреждениях с OpenSource лицензиями. Вне зависимости от того, кто указан автором - нашли в гражданском кодексе фишку, её и используем. Спасибо нашему юристу.

Так что мы выкрутились ;-) . Просто данная задача с 26 января висит - других вариантов не было. 

P.S. У меня сегодня возник новый кейс - как пройти СБ если используются докер контейнеры. Вот это юридический геморой я вам скажу полный.

**Comment by nixel2007** [comment]
@allustin отлично, рад слышать.

Тогда я актуализирую свой PR, оставив там xDD как владельца.
