### ISSUE TITLE
Перспективы проекта после выхода платформы 8.3.8

### ISSUE THREAD

**Issue by Infactum** [xDrivenDevelopment/precommit1c#68]
Думаю все читали, что начиная с 8.3.8 в платформе появится возможность выгрузку внешних печатных форм и отчетов в XML. Т.е. формально проект станет не нужен? Хотелось бы услышать мнение основных разработчиков проекта.
И вопрос номер 2, как следствие из этого (пока не стал выделять в отдельный issue). В случае, если проект планируется развивать после 8.3.8, то почему бы совсем не отказаться от зависимости в виде v8Reader и технологической платформы. По факту от v8Reader используется малая часть и переписать ее на тот же 1Script, который тут так любят не проблема.
Со своей стороны я хотел реализовать чистый Python форк, без каких-либо зависимостей, но по обозначенной выше причине пока это дело отложил.

**Comment by pumbaEO** [comment]
Зная любовь 1с к ручным действиям и любви к гвоздям, я пока не верю, что анонсированная фича будет без проблем работать. При этом я вижу скорей всего проблему в сборке обратно из исходников, особенно это скорей всего касаться будет типов реквизитов обработки, т.е. при сборке необходимо будет запускать на cf отдаленно похожий на тот в котором эта обработка создавалась, а не обходиться пустой базой.

В v8reader разбор построен на регулярках, 1script не поддерживает на текущий момент из коробки регулярки, переделывать на виндовые все равно остается проблема запуска разбора на linux, поэтому на 1script не переписывается.

**Comment by artbear** [comment]
@pumbaEO 
>1script не поддерживает на текущий момент из коробки регулярки
давно уже поддерживает :)

**Comment by artbear** [comment]
>Зная любовь 1с к ручным действиям и любви к гвоздям, я пока не верю, что анонсированная фича будет без проблем работать

+1

**Comment by nixel2007** [comment]
> > 1script не поддерживает на текущий момент из коробки регулярки

> давно уже поддерживает :)

Серьезно? Вот так новость! Нативно без ком-объекта?

**Comment by nixel2007** [comment]
> Т.е. формально проект станет не нужен?

Если фича открытия обработок прямо в исходниках действительно будет работать и все резко перейдут на 8.3.8 - то формально да.

А вот для всех, кто на 8.3.7 и ниже (даже на 8.2 до сих пор сидят, бедные люди) придется писать какие-то очередные костыли по сборке.

В общем, еще очень много вопросов. Даже структуру хранения не представили, может там будет все еще хуже.

**Comment by artbear** [comment]
Конечно, я реализовал на Net-объектах
[Приемочные тесты регулярных выражений для 1скрипт](https://bitbucket.org/EvilBeaver/1script/src/a03f0c79ccb4421cb4b343402fa94b710e1e888d/tests/regex.os?at=develop&fileviewer=file-view-default)

Например, 
```
	РегулярноеВыражение = Новый РегулярноеВыражение("\d\d");
	Совпало = РегулярноеВыражение.Совпадает("15");
	юТест.Проверить(Совпало, "Совпало 15");

	ИсходнаяСтрока = "S"+Символы.ПС+"s";

	РегулярноеВыражение = Новый РегулярноеВыражение("^S");
	юТест.Проверить(РегулярноеВыражение.Многострочный, "РегулярноеВыражение.Многострочный");

	КоллекцияСовпадений = РегулярноеВыражение.НайтиСовпадения(ИсходнаяСтрока);
	юТест.ПроверитьРавенство(2, КоллекцияСовпадений.Количество(), "КоллекцияСовпадений.Количество()");

```

**Comment by pumbaEO** [comment]
хм, да в linux рабоет Новый РегулярноеВыражение

**Comment by Infactum** [comment]
Тогда, полагаю, как минимум до релиза 8.3.8 неопределенность никуда не исчезнет.
Вопрос на 100% скриптовой (без V8Reader/v8unpack/1С) и соответственно полностью кроссплатформенной реализации precommit предлагаю оставить открытым. Мне просто хочется знать, интересно ли это кому-то кроме меня. Я правда пользуюсь только python версией..

**Comment by pumbaEO** [comment]
@Infactum если будет линуксовая версия хоть на питоне(стоящем по умолчанию) хоть на oscript - буду пользоваться с удовольствием, мне сейчас приходиться запускать для этого виртуалку с виндой.

**Comment by nixel2007** [comment]
> Конечно, я реализовал на Net-объектах
Приемочные тесты регулярных выражений для 1скрипт

В синтаксис-помощнике нет :(
Его можно как-то автоматически актуализировать по имеющимся методам?

**Comment by pumbaEO** [comment]
Тем более, что у меня того питона как гуталина 
![screenshot_15](https://cloud.githubusercontent.com/assets/166003/12582585/223543ec-c44f-11e5-8f9d-cd117148d65e.png)

**Comment by artbear** [comment]
>В синтаксис-помощнике нет :(
Его можно как-то автоматически актуализировать по имеющимся методам?

@EvilBeaver что скажешь? как добавить доку на сайт? в исходниках дока есть

**Comment by artbear** [comment]
@pumbaEO ты с картинкой не ошибся?
и откуда у сбербанка доп.пароль да еще с подтверждением :)  ?

**Comment by pumbaEO** [comment]
С картинкой ошибся. 
![screenshot_6](https://cloud.githubusercontent.com/assets/166003/12582682/9f34589c-c44f-11e5-9032-15a83d6f4c71.png)

**Comment by EvilBeaver** [comment]
И еще, коллеги, кажется, что вы не заметили главного: Именно благодаря precommit данный функционал появился в платформе. Наверное не только ему, но он свою роль сыграл, я уверен

**Comment by artbear** [comment]
@EvilBeaver +1

**Comment by EvilBeaver** [comment]
@nixel2007, В синтакс-помощнике нет, т.к. там только stable версия описана, а регэкспы сделали в дев.

**Comment by nixel2007** [comment]
@EvilBeaver понял.

**Comment by allustin** [comment]
Можно вернуться к обсуждению

* вышла также 1.2.0.beta EDT - функционал работы с внешними обработками отсутствует, хотя выгрузку в 8.3.8 добавили явно ради перехода на работу с внешними обработками в EDT
* некоторая часть внешних обработок сейчас, даже в типовых содержит неуправляемые формы - которые даже с выходом 8.3.8 в принципе не решаются.

Хуже того - как и предсказывал @pumbaEO 8.3.8 не решила всех проблем.
https://partners.v8.1c.ru/forum/topic/1466117

Для тех у кого нет доступа процитирую

```
В 8.3.8 при выгрузке/загрузки внешних обработок в исходники, внешние ссылки разрешаются относительно базы данных в которой запускается конфигуратор с ключами /DumpExternalDataProcessorOrReportToFiles . При этом, если использовать пустую базу, без каких либо метаданных, то внешние ссылки заменяются на строковое поле, как при выгрузке, так и при загрузке.

Данная функциональность не должна зависеть от метаданных базы, т.к. текстовое представление используемых типов есть в файле copyinfo, что позволяет обработки созданные разных в УТ11 использовать в ERP, в случаи совпадения представления типов.

Обязательное указание базы данных с правильными метаданным влечет за собой проблемы в виде постоянной синхронизации конфигурации разработчика и конфигурации в которой происходит сборка/разборка внешних обработок.
```

ну и пропажа справки 

```
Пустая база с указанием при создании ru --> Внешния обработка --> Разобрал на исходники --> создал пустую базу с en --> Загружаю из исходников справка пропадает.
```

Всё это как я понимаю связано с тем, что никто кроме нас и связанных с нами внешние обработки в виде исходников не хранит, хуже того, я так понимаю люди и расширения в исходниках также не хранят, даже на больших проектах из трех букв.

Учитывая:

* ночь и выходной
* явные подтверждения, что в материнской компании пока сами не пользуются функционалом
* "другие пионеры"

Предполагаю что precommit1C будет жить еще этот год точно.

Хотя мы хотим попробовать в некоторых проектах переход полностью на работу с исходниками, без бинарников. Но я думаю - это EPIC на этот год точно.

**Comment by allustin** [comment]
офтопик - "другие пионеры", это отсюда https://www.youtube.com/watch?v=rFQ6qiENcH4

**Comment by zeratulayuris** [comment]
Собственно, в #84 дописал скрипт для использования конфигуратора 1С, но проблем, указанных выше, это никак не решает - ссылки и справка по-прежнему будут потеряны. Для кого это не столь критично - уже можно использовать. Я пока останусь на v8Reader :)
@Infactum проект будет развиваться и дальше, кмк, потому что 1С не предлагает автоматизацию разборки/сборки ни для внешних отчетов/обработок, ни для конфигураций.

**Comment by zeratulayuris** [comment]
Обновил #84, теперь можно решить проблему со ссылками. Проблему со справкой завтра поищу на багтрекере 1С, если не найду - отправлю багрепорт.

**Comment by bf0rce** [comment]
Зашел посмотреть что происходит в проекте в связи с появлением 8.3.8, но оказалось, что здесь уже как полгода ведется обсуждение этого вопроса.

У меня, как обычно, свой велосипед. В комментариях на Инфостарте я уже как-то упоминал как мы версионируем юнит- и сценарные тесты с помощью типового хранилища. Если сообществу интересно, могу описать как я планировал при помощи 8.3.8 доставлять обработки тестирования через репозиторий на сервер сборки. 

Схему эту я еще не реализовывал. Возможно, она тоже имеет свои подводные камни или не заработает вообще, но, имхо, она может оказаться рабочей и решить проблему ссылок.

**Comment by pumbaEO** [comment]
Инетерсно. Всегда рад новым идеям. 

Сейчас я тестирую https://github.com/pumbaEO/vanessa-behavior-tets 
При инициализации у разработчика создаю 2 базы по умолчанию по путям ./build/ib и по пути ./build/ibservice которая используется для дальнейшей сборки/разборки внешних обработок. При этом сам разработчик заходит конфигуратором в базу ./build/ib и именно там ведет свою разработку.

**Comment by bf0rce** [comment]
@pumbaEO, да, идея очень похожа. 

1. Так как на начальном этапе все версионируется через хранилище, то в хранилище нужно создавать те объекты метаданных, на которые мы ссылаемся в обработках. Просто пустые, для ссылок. В вашем случае это та самая база ibservice, в которой, я так понимаю, приходится делать то же самое. 

1. Периодически на этой базе я прогоняю расширенную проверку конфигурации, чтобы понять на какие объекты ссылаются по коду. Но у нас тесты, в них реквизиты и табличные части используются редко. В общем же случае, разработчик должен сам позаботиться, чтобы его ссылки не потерялись. Во-первых, всегда выводится сообщение в окно сообщений, если что-то не найдено. Во-вторых, для верности, можно сделать сравнение/объединение с обработкой на диске.

1. Дальше работают уже знакомые механизмы, которые разбирают новую версию хранилища на исходники и фиксируют в git.

1. Теперь, если выгрузить эту обработку во внешнюю и разобрать конфигуратором на исходники, то моно увидеть, что отличий не много. На идентификаторы типов я внимания не обращаю, а в корневом файле заменяю DataProcessor -> ExternalDataProcessor, DataProcessorObject -> ExternalDataProcessorObject. После замены обработку уже можно загрузить из исходников (правда с ошибками, которые тоже решаются удалением неактуальных атрибутов корневого файла).

1. Итог. Имеем хранилище, которое зеркалится в git. На стороне сервера сборки нужно иметь скрипт, который пройдется по папке src/DataProcessors и найдет нужные нам обработки (например, по префиксу) или все. После этого сделает замены, очистит от мусора и соберет из них epf-ки. Собирать он их будет на той же конфигурации, из которой мы сделали обработки внешними.

А вообще, конечно, я ждал от 1С ключ для сохранения обработки из конфигурации на диск в бинарном виде. В нашу модель это бы уложилось с меньшими "затратами".

**Comment by pumbaEO** [comment]
Мне две вещи не нравятся:
1. Отстутствие git-flow 
2. Линейность списка обработок в метаданных, у меня допустим 50-70 внешних обработок, раскиданных по папкам по функционалам, а так будет простой линейный список.

**Comment by bf0rce** [comment]
Да, решение костыльное в любом случае.
1. git-flow в нашем случае пока не требуется. Но тут проще - отказался от хранилища и можно разрабатывать по правильному.
2. Линейность списка в какой-то мере можно пережить. В конфигураторе есть подсистемы, есть строка поиска. Собирать обработки можно также в соответствии с иерархией подсистем. Тут основная идея в наличии облегченно-обрезанной конфигурации с требуемыми типами. Обработки вполне можно хранить не в ней.

А вообще, правда. Иногда не хватает возможности в метаданных сделать группу обработок (здесь БСП, тут наши, тут типовые). Много где не хватает. В том же SQL сервере, когда смотришь на длинный список баз.

Кстати, а что если будет инструмент, который будет создавать конфигурацию для сборки обработок с нуля, пробегаясь по исходным кодам и выискивая ссылочные типы, которые будут необходимы? Разработчику, в данном случае, нужно сохранить обработку в XML из базы с полной конфигурацией, а далее скрипт соберет сначала цф-ник а потом и обработки.

**Comment by pumbaEO** [comment]
>  пробегаясь по исходным кодам и выискивая ссылочные типы, которые будут необходимы
имеешь ввиду пробегаясь по исходникам внешних обработок или же по исходникам конфигурации? 

С созданием с нуля конфигурации и загрузки ее в cf есть нюансы:
https://partners.v8.1c.ru/forum/t/1503964/m/1504008

**Comment by bf0rce** [comment]
Нет, я подразумевал, что нужно искать ссылочные типы только в исходных кодах обработок, а далее уже создавать описание объектов метаданных с нуля. Формы не нужны совсем, ведь, в 1с не бывает реквизитов с типом Форма. А конфигурация с обязательными метаданными нужна только для сборки.

**Comment by volodkindv** [comment]
Коллеги, вам интересен порт v8Reader на Python 3.5 ? (пока только декомпиляция)

**Comment by nixel2007** [comment]
Скорее на oscript. Но портировать с питона на оскрипт будет проще.

**Comment by volodkindv** [comment]
Тогда я просто оставлю это здесь.
Код полностью ужасен, т.к. я в питоне пока не очень. И содержит кучу отладочного мусора. Но надеюсь, что идея будет ясна.
Если удастся довести до ума, оформлю здесь отдельным проектом.
https://cloud.mail.ru/public/CDMc/vnboFuXJk

**Comment by allustin** [comment]
@volodkindv я честно признаюсь - побоялся скачивать странный zip файл ;-) тем более с mail.ru

**Comment by volodkindv** [comment]
@allustin мне почему-то не удалось прицепить файл сюда. "We don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or **ZIP**." (WTF??? Это ведь и есть ZIP)
На mail.ru лежит мое хранилище, которое удалось урвать по акции, когда они раздавали терабайт ))
Если все еще страшно, то можно смотреть здесь:
https://github.com/volodkindv/onecDecoder

**Comment by rsyuzyov** [comment]
@allustin это хороший человек, можно скачивать )
