### ISSUE TITLE
Зацикливание обхода каталогов при использовании v8files-extractor.os с ключами --compile --recursive

### ISSUE THREAD

**Issue by wizi4d** [xDrivenDevelopment/precommit1c#70]
Пример приводящий к зацикливанию:
```
oscript "..\utils\precommit1c\v8files-extractor.os" --compile "..\src\tests" "..\tests" --recursive
```

**Comment by nixel2007** [comment]
Из обсуждения https://github.com/wizi4d/TaskManagerFor1C/issues/7

**Comment by EvilBeaver** [comment]
Решение: добавить параметр Маска (второй по счету) в месте вызова метода НайтиФайлы.

**Comment by nixel2007** [comment]
@EvilBeaver "*.*"
Там суть в том, что нужны и файлы и каталоги

**Comment by EvilBeaver** [comment]
@nixel2007 ПолучитьМаскуВсеФайлы() - кроссплатформенный кошерный способ

**Comment by wizi4d** [comment]
@artbear прими пулреквест пожалуйста. Проверил на своей задаче, проблема решена.
