### ISSUE TITLE
Проверять/Включить правильную настройку переноса строк

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/precommit1c#78]
- [ ] Добавить проверку `git config --local core.autocrlf`на возврат false
- [ ] Добавить в readme описание правильной проверки переноса строк с ремаркой про local и global (рекомендовать!) ?
- [ ] Или сразу добавить установку `git config --local core.autocrlf false` при запуске precommit1c

Аналогично сделанной работе по `git config --local core.quotepath`

**Comment by zeratulayuris** [comment]
precommit1c с ключом --install уже устанавливает quotepath и longpaths.
Думаю, есть смысл все три настройки привести к одному виду.

**Comment by artbear** [comment]
В #125 решили этого не делать.
Закрываю
