### ISSUE TITLE
Установка не через git

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/precommit1c#81]
Сейчас для того чтобы иметь возможность инициализировать сабмодули необходимо выкачивать прекоммит именно как гит-репозиторий. Скачивание zip-архива не позволит воспользоваться прекоммитом вообще. 

Предлагаю вместе с релизом публиковать zip-архив, в котором будет включён сам прекоммит и нужная не-гит версия v8reader. 
Это существенно ускорит время установки прекоммита в нужный репо - скачали zip, распаковали в hooks - работает (максимум ещё задали core.quotepath).

**Comment by allustin** [comment]
Хм. Есть такой плагин к Jenkins - называется GitHub Publisher. Можно с помощью него. Для GitLab не помню есть подобное или нет.

Что касается Issue - есть 3 шага как мне кажется

* download
* install in repo
* update in repo

может пора уже посмотреть в сторону opm, то есть кейс следующий

```
opm install precommit
cd my-git-repo
precommit install-or-update
```

@nixel2007 сумбурно ?

**Comment by allustin** [comment]
команда `opm install precommit` и будет скачивать пакет, а публикация пакета будет как-то с помощью сервера сборок. Только нужно @EvilBeaver спросить как это будет

**Comment by nixel2007** [comment]
Пока не думал в сторону opm.
Изначально я (уже) начал пилить некий build.os, который просто будет формировать precommit.zip, готовый к загрузке в "релиз" гитхаба.

opm требует "долгого" времени на доработку (по крайней мере до такого состояния, каким я хочу его видеть).

build.os - быстрое решение, которое может помочь уже сейчас. итеративный подход, м?

если возражений нет, то продолжу пилить build.os :)

**Comment by nixel2007** [comment]
> команда opm install precommit и будет скачивать пакет,

мое видение - скачивать его в предполагаемый oscript_modules и выполнять postinstall-скрипт, который скопирует его в хуки.
потому что precommit1c - это не библиотека. его нельзя #Использовать =/

**Comment by nixel2007** [comment]
@allustin ааа, я понял... ты хочешь устанавливать precommit глобально... и устанавливать его через саму команду прекоммита...

Хорошая идея :)

**Comment by artbear** [comment]
@allustin Да, мне также нравится идея установки пакета на машину, а затем развертывание в конкретном репо.
@nixel2007 почему opm-путь это долго?
@EvilBeaver что скажешь?

**Comment by nixel2007** [comment]
@artbear потому что его надо очень сильно дописывать и возможно переписывать.
Надеюсь, что когда-нибудь у меня и @EvilBeaver дойдут до него руки.

**Comment by EvilBeaver** [comment]
А собсна что его переписывать? Для текущей задачи пакет вполне пойдет. @nixel2007 нужны спецификации - что именно нужно, фичи. А переписать не так долго там. Там проблемы не с кодом, а с концепцией. Я за пакетирование, как таковое. Это развивает экосистему

**Comment by nixel2007** [comment]
> нужны спецификации - что именно нужно, фичи. А переписать не так долго там. Там проблемы не с кодом, а с концепцией.

я это и имел ввиду :)

**Comment by artbear** [comment]
@nixel2007 Что именно переписывать?
я лично юзал гитсинк в режиме пакета.
просто и удобно работает. нужно только сделать простой файл-описание пакета.

**Comment by allustin** [comment]
маленький полуофтопик... а может v8unpack включить в поставку oscript в каталоге bin ?
он тогда сразу в path пропишется ;-)

я понимаю что костыль... но может это так сказать ускорит процесс ;-)

**Comment by pumbaEO** [comment]
вот щас линуксоидам обидно было.

**Comment by nixel2007** [comment]
На v8unpack вообще непонятно что с лицензией. Его и в прекоммит-то нельзя включать, если по-хорошему.

**Comment by allustin** [comment]
@pumbaEO где обидел то - есть же сборка v8unpack для nix, ее туда же в oscript.

@nixel2007 мы уже 6 лет этот тонкий момент опускаем... и все как бы делают вид что не знаю что происходит.
