### ISSUE TITLE
Убрать проверку --local core.quotepath , если уже установленно global

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/precommit1c#82]
В случаи глобальной установки этого параметра, все равно проверяет каждый раз именно настройку этого репозитария, что ни есть удобно. 
Тем более, на win средах и для 1с - это лучше глобально устанавливать.

**Comment by EvilBeaver** [comment]
А в гите нельзя получить effective настройку? Ну т.е. проверить вообще есть ли флаг, независимо от уровня global/local?

**Comment by pumbaEO** [comment]
в новом гите есть.

**Comment by allustin** [comment]
@EvilBeaver я попробовал сделать примерно вот такое к прошлому воркшопу

https://github.com/allustin/note-checker/blob/master/check-note-dev.os

то есть некий скрипт автоматизатор проверки компьютера/виртуалки правильного ;-) разработчика.

к новому воркшопу я его добью - за май я думаю.
этот же скрипт будет глобально устанавливать git config --global core.qoutepath

а то если честно - подзадолбало уже документировать и видеролики записывать.

Общая идея - чтобы компьютеры разработчиков соответствовали некому стандарту версий и установленных программ.

**Comment by pumbaEO** [comment]
https://github.com/xDrivenDevelopment/precommit1c/blob/develop/v8files-extractor.os#L359
в теории достаточно убрать --local и он вернет текущее значение с учетом
прирорета

21 апреля 2016 г., 21:29 пользователь Alexey Lustin <
notifications@github.com> написал:

> @EvilBeaver <https://github.com/EvilBeaver> я попробовал сделать примерно
> вот такое к прошлому воркшопу
>
> https://github.com/allustin/note-checker/blob/master/check-note-dev.os
>
> то есть некий скрипт автоматизатор проверки компьютера/виртуалки
> правильного ;-) разработчика.
>
> к новому воркшопу я его добью - за май я думаю.
> этот же скрипт будет глобально устанавливать git config --global
> core.qoutepath
>
> а то если честно - подзадолбало уже документировать и видеролики
> записывать.
>
> Общая идея - чтобы компьютеры разработчиков соответствовали некому
> стандарту версий и установленных программ.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/precommit1c/issues/82#issuecomment-213054755>
>



-- 
З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by artbear** [comment]
Ага, подтверждаю
`git config core.quotepath` вернет либо глобальное либо локальное состояние
