### ISSUE TITLE
Информация об ошибке поиска v8Reader

### ISSUE THREAD

**Issue by allustin** [xDrivenDevelopment/precommit1c#86]
https://github.com/xDrivenDevelopment/precommit1c/blob/develop/v8files-extractor.os#L276

Сейчас если пользователи забыли сделать инициализацию подмодулей после клонирования выводится неинформативное сообщение об ошибке, примерно так.

`ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os / Ошибка в строке: 276 / [Failed] Ожидали, что проверяемое значение (Ложь) является ИСТИНОЙ.}`

Необходим небольшой хотфикс с добавлением информации `Не установлен v8reader из пакета precommit` или что-то подобное, побуждающее пользователей читать README.md

`Ожидаем.Что(Значение, "Флаг режима суперсилы должен быть включен").ЕстьИстина()`

**Comment by allustin** [comment]
@nixel2007 кстати - напомни, в каком бранче обсуждается инсталятор ?, потому как проблема подмодулей с переходом на исталятор уйдет.

**Comment by nixel2007** [comment]
@allustin вот отсюда https://github.com/xDrivenDevelopment/precommit1c/issues/3#issuecomment-220652430 и далее по тексту
