### ISSUE TITLE
Разбор исходных текстов с новым именем исходников модулей

### ISSUE THREAD

**Issue by allustin** [xDrivenDevelopment/precommit1c#9]
Есть новость, что 1С будет использовать расширение файлов НЕ txt. В качестве проактивной меры - не стоит ли нам перейти на разбор модулей в новом расширении

**Comment by nixel2007** [comment]
Таки bsl.
```
Реализована возможность выгрузки и загрузки конфигурации в файлы в иерархическом формате.
Имя нового объекта конфигурации ограничено 80 символами. Существующие объекты конфигурации могут иметь имена длиннее 80 символов, но только до любой попытки редактирования такого имени.
Файл с модулем на встроенном языка имеет расширение .bsl.
```
http://downloads.v8.1c.ru/content//Platform/8_3_7_1633/1cv8upd.htm

**Comment by nixel2007** [comment]
Ап.
Я тут немного со своей колокольни еще смотрю (количество репозиториев с `bsl` от этого должно возрасти).

Прекоммит перед распаковкой очищает каталог, в который он будет распаковывать. Т.е. старых лишних txt-файлов у нас не останется.
Вопрос с историей - обычное переименование файла гитом зафиксируется как удаление файла и создание нового. 
Бампнуть версию precommit, описать рекомендуемые действия по переходу - `git mv` для ряда txt, в идеале отдельный скрипт обновления.
Ну или совсем сурово - при использовании режима `--git-precommit` сначала сделать `git mv` для таких файлов (на мой взгляд, по производительности ударит, да и нужно оно по сути один раз).
