### ISSUE TITLE
Документировать форматы выгрузки макетов

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/precommit1c#91]
@bambr1975 Подскажешь?

**Comment by bambr1975** [comment]
https://github.com/xDrivenDevelopment/v8Reader/blob/master/src/V8Reader/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/module#L4530 (строки 4530 - 4562) отдельно выгружаются только макеты типов М6, М0 и М4 (компоновка, табличный документ и текстовый документ)

**Comment by artbear** [comment]
В каком виде выгружаются?
mxl копируется в mxl.txt, верно ?

**Comment by bambr1975** [comment]
Ответ скорректирован.  Если в параметрах запуска есть convert-mxl2txt, то да, копируется

**Comment by artbear** [comment]
>Остальное тоже выгружается отдельно, но в текстовом виде.

Макет ДвоичныеДанные выгружаются в текстовик?

**Comment by bambr1975** [comment]
угу. Женя сказал, что так будет правильнее с учетом того, чтобы github показывал изменения))))

**Comment by bambr1975** [comment]
я:
а можно для типов ДвоичныеДанные (М1), HTMLДокумент (М3), и ActiveDocument (М2) у меня будет сохраняться файл без расширения?
Евгений Сосна (shenjasosna@gmail.com)
тогда не будет понятно что это за макет, если будет без расширения.
я:
а так было понятно, когда они все были с txt?
Евгений Сосна (shenjasosna@gmail.com)
Нет, но тогда может им как раз и добавить правильные расширения?
я:
правильные - это какие? 
Евгений Сосна (shenjasosna@gmail.com)
html - html
bin - двоичные данные
я:
они все являются base64
Евгений Сосна (shenjasosna@gmail.com)
хм, это хуже .
Тогда и вправду лучше txt , тогда можно отрыть текстовым редактором без проблем.
я:
Может, тогда их сразу и извлекать из base64?
Там правда могут быть вложения)))
у Html
Евгений Сосна (shenjasosna@gmail.com)
Теперь стало понятно почему txt - чисто, что-бы проще было открыть в текстовом редакторе.

**Comment by zeratulayuris** [comment]
Добавил информацию в readme
