### ISSUE TITLE
Не помещаются исходники обработки в индекс git, если в названии файла два пробела

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/precommit1c#92]
originaly reported by @MaximGoncharov in https://github.com/pumbaEO/precommit1c/issues/20

> Есть обработка имя "МояОбработка  ДваПробелаВНазвании.epf"
Если запустить коммит по такому файлу, то исходники все в индекс автоматом не попадают и приходиться их повторно коммитить

**Comment by nixel2007** [comment]
@MaximGoncharov

Вроде проблема должна быть решена в последнем ночнике oscript (если он был выложен, /cc @EvilBeaver).
Проверьте, пожалуйста.

**Comment by EvilBeaver** [comment]
Ночник-то я выложу, а переименовать в один пробел наверное будет полезно, все-таки )

**Comment by MaximGoncharov** [comment]
а где ваши ночники то брать?

**Comment by nixel2007** [comment]
@MaximGoncharov http://oscript.io/downloads

**Comment by MaximGoncharov** [comment]
так на этом сайте я смотрели и там стоит что сборка от 30.06.2016

**Comment by MaximGoncharov** [comment]
на главной странице

**Comment by nixel2007** [comment]
![image](https://cloud.githubusercontent.com/assets/1132840/17802466/23a76448-65f9-11e6-949d-1b6499ef2706.png)

От 30.06 - это просто статья. Ночные сборки публикуются, внезапно, еженочно.

**Comment by MaximGoncharov** [comment]
да всё понял, скачал, проверил. Работает когда в имени файла есть несколько пробелов. Спасибо.
