### ISSUE TITLE
Отладочный лог cmdline при запуске

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/precommit1c#94]
Есть в v8files-extractor следущий код:

https://github.com/xDrivenDevelopment/precommit1c/blob/develop/v8files-extractor.os#L50-L52

Для чего это и можно ли убрать? Дебаг логи, включенные по умолчанию, как-то странно.

**Comment by nixel2007** [comment]
Для быстрого разрешения проблемных ситуаций при запуске. Чтобы не надо было переделывать хук или менять скрипт. Решение спорное, согласен.
Может добавим ключ -debug или -verbose?

**Comment by artbear** [comment]
Предлагаю ключ -verbose

**Comment by zeratulayuris** [comment]
@artbear вроде как закрылось вместе с изменением поведения logos.

**Comment by artbear** [comment]
>вроде как закрылось вместе с изменением поведения logos.

@zeratulayuris Не совсем.

Управлять-то отладкой мы можем, но не совсем удобно :)

Фактически управлять через переменные окружения мы не можем, т.к. скрипт стартует из команды гита, которой не так просто передать переменную окружения.

А вот управление логами через файл настройки логов для логоса мы можем, да.

И опять есть "НО" - файл настройки логов должен лежать рядом с запускаемым скриптом.
Или я ошибаюсь?

А в этом случае нужно обеспечить формирование подобного файла в каждом (или конкретном нужном) репозитории.
что пока сделать автоматически нельзя.

Как-то так.

**Comment by nixel2007** [comment]
в чем проблема с передачей переменных окружения сквозь команду гита? устанавливаем переменную в консоли через SET, выполяняем команду git, она делает subprocess с передачей переменных окружения к оскрипту, в оскрипте все переменные работают.

ну, в теории по крайней мере. если оно так не работает, то явно где-то что-то неправильно настроено на уровне запуска процессов.

**Comment by zeratulayuris** [comment]
Только что для теста установил свежий precommit1c в новый репозиторий. Если установить переменную окружения и выполнить коммит, то отладочные логи отлично формируются и для cmdline.

**Comment by artbear** [comment]
Да, уже давно выполнено.
Закрываю
