### ISSUE TITLE
Убрать сервисную базу из репозитория

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/precommit1c#96]
Предлагаю убрать сервисную базу из репозитория.

Ее вполне можно создавать автоматически при ее отсутствии. Каталог в репо стоит так же добавить в гит игнор.

Это решит две проблемы:
1) В базе иногда что-то меняется, из-за этого прекоммит в режиме сабмодуля становится "dirty" и его обновление затрудняется.
2) Чуть упростится установка - не надо копировать в хуки базу, не надо ее поставлять в zip

**Comment by pumbaEO** [comment]
Только создавать сервисную базу 1 раз, для всего процесса, не для каждого вызова разбора внешней обработки, где-нибудь в temp.

**Comment by nixel2007** [comment]
@pumbaEO да, естественно. Создавать ее можно в том же месте, где она сейчас лежит, просто заигнорить ее под гитом и вся недолга.

**Comment by EvilBeaver** [comment]
Вдруг несколько прекомимтов попытаются ее одновременно создавать, конфликтовать начнут

**Comment by nixel2007** [comment]
@EvilBeaver несколько прекоммитов, подключенных к одному и тому же репозиторию?

**Comment by EvilBeaver** [comment]
В схеме с 1 базой я так понял, что 1 база на все репы, возможные на компе. Я ошибся?

**Comment by pumbaEO** [comment]
Ну тогда простой ключ - база по дефолту или же указываем свой путь где хотим, что-бы база создалась и можно развлекаться с этим досхочу.

**Comment by nixel2007** [comment]
@EvilBeaver нет, как и раньше. У каждого репа своя база. Лежит так же, в хуках. Просто не в гите прекоммита как такового.

**Comment by EvilBeaver** [comment]
аа. Тогда стопицот плюсов.

**Comment by EvilBeaver** [comment]
Коллеги, а покажите мне, где в коде вообще используется сервисная база? Ее же и так нет в v8files-extractor.os

**Comment by nixel2007** [comment]
@EvilBeaver хм... да, там создается временная база каждый раз...

**Comment by nixel2007** [comment]
что ж это выходит, мы ее тащим с питоноверсии просто так?

**Comment by pumbaEO** [comment]
а че она тогда изменяется.

**Comment by nixel2007** [comment]
а леший ее знает...

**Comment by EvilBeaver** [comment]
Ну вот я и помню, что когда переписывал на оскрипт, то использовал базу, создаваемую внутри v8runner

**Comment by artbear** [comment]
Да, убираем.

**Comment by nixel2007** [comment]
@EvilBeaver закрываем?

**Comment by EvilBeaver** [comment]
@nixel2007 да
