### ISSUE TITLE
precommit1c --install Подскажите, что делаю не так? 

### ISSUE THREAD

**Issue by BlizD** [xDrivenDevelopment/precommit1c#99]
Подскажите, что делаю не так?

Пытаюсь выполнить команду: 
`d:\Cloud\Dev\GitRep\BlizD_xUnitFor1c>precommit1c --install`

Выдает следующее:

> ИНФОРМАЦИЯ - precommit1c v2.0.5
> 
> ОТЛАДКА - Добавляю позиционный параметр ПутьВходящихДанных
> ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
> ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
> ОТЛАДКА - Добавляю параметр-флаг --remove-orig-bin-files
> ОТЛАДКА - Добавляю позиционный параметр ПутьВходящихДанных
> ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
> ОТЛАДКА - Добавляю параметр-флаг --recursive
> ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\cmdline\src\cmdline.os / Ошибка в строке: 91 / Неизвестн
> ая команда: --install}
> 
> d:\Cloud\Dev\GitRep\BlizD_xUnitFor1c>

**Comment by nixel2007** [comment]
Прекоммит установлен с опм?

**Comment by EvilBeaver** [comment]
Ощущение, что какой-то старый прекоммит

**Comment by nixel2007** [comment]
2.0.5 нет в мастере

**Comment by EvilBeaver** [comment]
Я перед вебинаром ставил через opm с хаба, он работал

**Comment by BlizD** [comment]
Да ставил через opm

**Comment by nixel2007** [comment]
@BlizD выложи, пожалуйста, скрипт v8files-extractor, который скачался с опм. он должен лежать в programm files x86/OneScript/lib/precommit1c

**Comment by nixel2007** [comment]
@BlizD в opm выложено исправление.
выполни `opm update precommit1c` для обновления. После этого `precommit --install` должен заработать

**Comment by BlizD** [comment]
@nixel2007 Да, все отработало, спасибо.
